{
  id: 'gk-his-ww2bg-6',
  type: 'mcq',
  category: 'history',
  topicId: 'his-world-ww2-background',
  subject: 'history_geography',
  prompt: 'Chính sách Kinh tế mới (NEP) ở nước Nga Xô viết được thực hiện bắt đầu từ năm nào?',
  options: ['1917', '1921', '1925', '1929'],
  correctAnswer: '1921',
  explanation: 'Tháng 3/1921, Đảng Bônsêvích Nga quyết định thực hiện Chính sách Kinh tế mới (NEP) do Lênin đề xướng nhằm khôi phục kinh tế sau chiến tranh.',
  difficulty: 1,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-ww2bg-7',
  type: 'mcq',
  category: 'history',
  topicId: 'his-world-ww2-background',
  subject: 'history_geography',
  prompt: 'Ai là người đề xướng Chính sách Kinh tế mới (NEP) ở nước Nga Xô viết?',
  options: ['Lênin', 'Xtalin', 'Tơrốtxki', 'Kirốp'],
  correctAnswer: 'Lênin',
  explanation: 'Lênin là người đề xướng Chính sách Kinh tế mới (NEP) năm 1921, thay thế chính sách cộng sản thời chiến.',
  difficulty: 1,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-ww2bg-8',
  type: 'mcq',
  category: 'history',
  topicId: 'his-world-ww2-background',
  subject: 'history_geography',
  prompt: 'Liên bang Cộng hòa Xã hội chủ nghĩa Xô viết (Liên Xô) được thành lập vào ngày tháng năm nào?',
  options: ['7/11/1917', '30/12/1922', '21/1/1924', '1/1/1925'],
  correctAnswer: '30/12/1922',
  explanation: 'Ngày 30/12/1922, Liên bang Cộng hòa Xã hội chủ nghĩa Xô viết (Liên Xô) chính thức được thành lập.',
  difficulty: 1,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-ww2bg-9',
  type: 'mcq',
  category: 'history',
  topicId: 'his-world-ww2-background',
  subject: 'history_geography',
  prompt: 'Mục tiêu chính của công cuộc công nghiệp hóa xã hội chủ nghĩa ở Liên Xô là gì?',
  options: [
    'Biến Liên Xô từ một nước nông nghiệp thành một nước công nghiệp',
    'Mở rộng lãnh thổ ra toàn châu Âu',
    'Xây dựng quân đội mạnh nhất thế giới',
    'Phát triển ngành du lịch quốc tế'
  ],
  correctAnswer: 'Biến Liên Xô từ một nước nông nghiệp thành một nước công nghiệp',
  explanation: 'Thông qua các kế hoạch 5 năm bắt đầu từ 1928, Liên Xô thực hiện công nghiệp hóa nhằm biến đất nước từ nông nghiệp lạc hậu thành cường quốc công nghiệp.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-ww2bg-10',
  type: 'mcq',
  category: 'history',
  topicId: 'his-world-ww2-background',
  subject: 'history_geography',
  prompt: 'Cuộc khủng hoảng kinh tế thế giới 1929-1933 bùng nổ đầu tiên ở nước nào?',
  options: ['Mỹ', 'Anh', 'Đức', 'Pháp'],
  correctAnswer: 'Mỹ',
  explanation: 'Cuộc khủng hoảng kinh tế thế giới bùng nổ đầu tiên ở Mỹ vào tháng 10/1929, sau đó lan rộng ra toàn thế giới tư bản.',
  difficulty: 1,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-ww2bg-11',
  type: 'mcq',
  category: 'history',
  topicId: 'his-world-ww2-background',
  subject: 'history_geography',
  prompt: 'Sự kiện "Ngày thứ Năm đen tối" đánh dấu sự sụp đổ của thị trường chứng khoán New York diễn ra vào ngày nào?',
  options: ['24/10/1929', '4/9/1929', '3/2/1930', '1/9/1939'],
  correctAnswer: '24/10/1929',
  explanation: 'Ngày 24/10/1929, thị trường chứng khoán New York sụp đổ, mở đầu cho cuộc đại khủng hoảng kinh tế thế giới 1929-1933.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-ww2bg-12',
  type: 'mcq',
  category: 'history',
  topicId: 'his-world-ww2-background',
  subject: 'history_geography',
  prompt: 'Cuộc khủng hoảng kinh tế thế giới kéo dài trong khoảng thời gian nào?',
  options: ['1929-1933', '1918-1923', '1936-1939', '1939-1945'],
  correctAnswer: '1929-1933',
  explanation: 'Cuộc đại khủng hoảng kinh tế thế giới diễn ra từ năm 1929 đến năm 1933, gây hậu quả nặng nề cho các nước tư bản.',
  difficulty: 1,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-ww2bg-13',
  type: 'mcq',
  category: 'history',
  topicId: 'his-world-ww2-background',
  subject: 'history_geography',
  prompt: 'Để thoát khỏi khủng hoảng kinh tế 1929-1933, các nước Đức, Italia, Nhật Bản đã lựa chọn con đường nào?',
  options: [
    'Thiết lập chế độ độc tài phát xít',
    'Thực hiện Chính sách Kinh tế mới',
    'Tiến hành cải cách dân chủ',
    'Gia nhập Hội Quốc liên'
  ],
  correctAnswer: 'Thiết lập chế độ độc tài phát xít',
  explanation: 'Do không có hoặc có ít thuộc địa, thiếu vốn và nguyên liệu, Đức, Italia, Nhật Bản đã chọn con đường phát xít hóa bộ máy nhà nước để thoát khủng hoảng.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-ww2bg-14',
  type: 'mcq',
  category: 'history',
  topicId: 'his-world-ww2-background',
  subject: 'history_geography',
  prompt: 'Tổng thống Mỹ nào đã thực hiện "Chính sách mới" (New Deal) để đưa nước Mỹ thoát khỏi khủng hoảng kinh tế?',
  options: ['Ru-dơ-ven (Roosevelt)', 'Wilson', 'Truman', 'Lincoln'],
  correctAnswer: 'Ru-dơ-ven (Roosevelt)',
  explanation: 'Tổng thống Ru-dơ-ven đã thực hiện "Chính sách mới" nhằm giải quyết nạn thất nghiệp, phục hồi kinh tế, giúp Mỹ thoát khỏi khủng hoảng bằng con đường cải cách dân chủ.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-ww2bg-15',
  type: 'mcq',
  category: 'history',
  topicId: 'his-world-ww2-background',
  subject: 'history_geography',
  prompt: 'Hít-le lên nắm quyền Thủ tướng Đức, mở đầu thời kỳ thống trị của chủ nghĩa phát xít ở Đức vào ngày nào?',
  options: ['30/1/1933', '1/9/1939', '22/6/1941', '7/12/1941'],
  correctAnswer: '30/1/1933',
  explanation: 'Ngày 30/1/1933, Hít-le được cử làm Thủ tướng Đức, đánh dấu việc chủ nghĩa phát xít chính thức thắng thế ở Đức.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-ww2bg-16',
  type: 'mcq',
  category: 'history',
  topicId: 'his-world-ww2-background',
  subject: 'history_geography',
  prompt: 'Đảng phái nào đã đưa Hít-le lên nắm quyền ở Đức?',
  options: ['Đảng Quốc xã', 'Đảng Xã hội dân chủ', 'Đảng Cộng sản Đức', 'Đảng Trung tâm'],
  correctAnswer: 'Đảng Quốc xã',
  explanation: 'Đảng Quốc xã (Đảng Công nhân Đức Quốc gia Xã hội chủ nghĩa) do Hít-le đứng đầu đã đưa hắn lên nắm quyền, thiết lập chế độ độc tài phát xít.',
  difficulty: 1,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-ww2bg-17',
  type: 'mcq',
  category: 'history',
  topicId: 'his-world-ww2-background',
  subject: 'history_geography',
  prompt: 'Mút-xô-li-ni (Mussolini) và Đảng Phát xít lên cầm quyền ở Italia bằng sự kiện nào, năm nào?',
  options: [
    'Cuộc "Tiến quân vào Rôma" năm 1922',
    'Cuộc đảo chính năm 1929',
    'Cuộc bầu cử năm 1933',
    'Cuộc nổi dậy năm 1919'
  ],
  correctAnswer: 'Cuộc "Tiến quân vào Rôma" năm 1922',
  explanation: 'Năm 1922, Mút-xô-li-ni tổ chức cuộc "Tiến quân vào Rôma", buộc nhà vua phải trao quyền, thiết lập chế độ độc tài phát xít ở Italia.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-ww2bg-18',
  type: 'mcq',
  category: 'history',
  topicId: 'his-world-ww2-background',
  subject: 'history_geography',
  prompt: 'Nhật Bản đã tiến hành xâm lược vùng đất nào của Trung Quốc vào năm 1931 để giải quyết khủng hoảng kinh tế?',
  options: ['Vùng Đông Bắc (Mãn Châu)', 'Vùng Hoa Nam', 'Đảo Hải Nam', 'Bán đảo Sơn Đông'],
  correctAnswer: 'Vùng Đông Bắc (Mãn Châu)',
  explanation: 'Năm 1931, quân phiệt Nhật Bản đã tiến hành xâm lược vùng Đông Bắc Trung Quốc (Mãn Châu), mở đầu quá trình quân phiệt hóa, phát xít hóa bộ máy nhà nước.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-ww2bg-19',
  type: 'mcq',
  category: 'history',
  topicId: 'his-world-ww2-background',
  subject: 'history_geography',
  prompt: 'Ba nước nào hình thành nên khối liên minh phát xít (Trục) trước Chiến tranh thế giới thứ hai?',
  options: ['Đức - Italia - Nhật Bản', 'Đức - Áo - Hung', 'Anh - Pháp - Mỹ', 'Đức - Pháp - Nhật Bản'],
  correctAnswer: 'Đức - Italia - Nhật Bản',
  explanation: 'Đức, Italia, Nhật Bản là ba nước hình thành khối liên minh phát xít (phe Trục), chuẩn bị gây ra Chiến tranh thế giới thứ hai.',
  difficulty: 1,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-ww2bg-20',
  type: 'mcq',
  category: 'history',
  topicId: 'his-world-ww2-background',
  subject: 'history_geography',
  prompt: 'Hiệp ước Chống Quốc tế Cộng sản (Hiệp ước Tam cường) giữa Đức, Italia, Nhật Bản được ký kết vào năm nào?',
  options: ['1937', '1929', '1933', '1941'],
  correctAnswer: '1937',
  explanation: 'Năm 1937, Đức, Italia, Nhật Bản ký Hiệp ước Chống Quốc tế Cộng sản, chính thức hình thành khối liên minh phát xít (trục Béc-lin - Rô-ma - Tô-ky-ô).',
  difficulty: 3,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-ww2-6',
  type: 'mcq',
  category: 'history',
  topicId: 'his-world-ww2',
  subject: 'history_geography',
  prompt: 'Chiến tranh thế giới thứ hai bùng nổ khi Đức tấn công nước nào vào ngày 1/9/1939?',
  options: ['Ba Lan', 'Pháp', 'Liên Xô', 'Tiệp Khắc'],
  correctAnswer: 'Ba Lan',
  explanation: 'Ngày 1/9/1939, Đức tấn công Ba Lan, mở đầu Chiến tranh thế giới thứ hai.',
  difficulty: 1,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-ww2-7',
  type: 'mcq',
  category: 'history',
  topicId: 'his-world-ww2',
  subject: 'history_geography',
  prompt: 'Anh và Pháp tuyên chiến với Đức vào ngày nào, sau khi Đức tấn công Ba Lan?',
  options: ['3/9/1939', '1/9/1939', '22/6/1941', '7/12/1941'],
  correctAnswer: '3/9/1939',
  explanation: 'Ngày 3/9/1939, thực hiện cam kết đồng minh với Ba Lan, Anh và Pháp tuyên chiến với Đức.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-ww2-8',
  type: 'mcq',
  category: 'history',
  topicId: 'his-world-ww2',
  subject: 'history_geography',
  prompt: 'Đức tấn công Liên Xô, mở ra mặt trận Xô - Đức vào ngày tháng năm nào?',
  options: ['22/6/1941', '1/9/1939', '7/12/1941', '6/6/1944'],
  correctAnswer: '22/6/1941',
  explanation: 'Ngày 22/6/1941, Đức bất ngờ tấn công Liên Xô, mở ra mặt trận Xô - Đức trong Chiến tranh thế giới thứ hai.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-ww2-9',
  type: 'mcq',
  category: 'history',
  topicId: 'his-world-ww2',
  subject: 'history_geography',
  prompt: 'Nhật Bản bất ngờ tấn công căn cứ hải quân Mỹ tại Trân Châu Cảng vào ngày nào?',
  options: ['7/12/1941', '1/9/1939', '22/6/1941', '9/8/1945'],
  correctAnswer: '7/12/1941',
  explanation: 'Ngày 7/12/1941, Nhật Bản bất ngờ tấn công Trân Châu Cảng (Hawaii, Mỹ), kéo Mỹ chính thức tham gia Chiến tranh thế giới thứ hai.',
  difficulty: 1,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-ww2-10',
  type: 'mcq',
  category: 'history',
  topicId: 'his-world-ww2',
  subject: 'history_geography',
  prompt: 'Trận đánh nào được xem là bước ngoặt, làm xoay chuyển tình thế trên mặt trận Xô - Đức (1942-1943)?',
  options: ['Trận Xta-lin-grát (Stalingrad)', 'Trận Mát-xcơ-va', 'Trận Béc-lin', 'Trận Cuốc-xcơ'],
  correctAnswer: 'Trận Xta-lin-grát (Stalingrad)',
  explanation: 'Chiến thắng Xta-lin-grát (1942-1943) của Hồng quân Liên Xô là bước ngoặt xoay chuyển cục diện chiến tranh, đẩy phe phát xít vào thế phòng ngự.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-ww2-11',
  type: 'mcq',
  category: 'history',
  topicId: 'his-world-ww2',
  subject: 'history_geography',
  prompt: 'Quân Đồng minh đổ bộ lên bờ biển Noóc-măng-đi (Normandy) mở mặt trận thứ hai ở Tây Âu vào ngày nào?',
  options: ['6/6/1944', '9/5/1945', '6/8/1945', '2/9/1945'],
  correctAnswer: '6/6/1944',
  explanation: 'Ngày 6/6/1944, quân Đồng minh đổ bộ lên Noóc-măng-đi (Pháp), mở mặt trận thứ hai ở Tây Âu, góp phần đẩy nhanh sự sụp đổ của phát xít Đức.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-ww2-12',
  type: 'mcq',
  category: 'history',
  topicId: 'his-world-ww2',
  subject: 'history_geography',
  prompt: 'Phát xít Đức tuyên bố đầu hàng Đồng minh không điều kiện vào ngày nào?',
  options: ['9/5/1945', '1/9/1939', '15/8/1945', '2/9/1945'],
  correctAnswer: '9/5/1945',
  explanation: 'Ngày 9/5/1945, phát xít Đức ký văn kiện đầu hàng không điều kiện, chấm dứt chiến tranh ở châu Âu.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-ww2-13',
  type: 'mcq',
  category: 'history',
  topicId: 'his-world-ww2',
  subject: 'history_geography',
  prompt: 'Mỹ đã ném hai quả bom nguyên tử xuống hai thành phố nào của Nhật Bản?',
  options: ['Hi-rô-si-ma và Na-ga-xa-ki', 'Tô-ky-ô và Ô-xa-ka', 'Hi-rô-si-ma và Tô-ky-ô', 'Na-ga-xa-ki và Kyoto'],
  correctAnswer: 'Hi-rô-si-ma và Na-ga-xa-ki',
  explanation: 'Ngày 6/8/1945 và 9/8/1945, Mỹ lần lượt ném hai quả bom nguyên tử xuống Hi-rô-si-ma và Na-ga-xa-ki của Nhật Bản.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-ww2-14',
  type: 'mcq',
  category: 'history',
  topicId: 'his-world-ww2',
  subject: 'history_geography',
  prompt: 'Nhật Bản tuyên bố đầu hàng Đồng minh không điều kiện vào ngày nào, kết thúc Chiến tranh thế giới thứ hai?',
  options: ['15/8/1945', '9/5/1945', '2/9/1945', '6/8/1945'],
  correctAnswer: '15/8/1945',
  explanation: 'Ngày 15/8/1945, Nhật Bản tuyên bố đầu hàng Đồng minh không điều kiện, Chiến tranh thế giới thứ hai kết thúc.',
  difficulty: 1,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-ww2-15',
  type: 'mcq',
  category: 'history',
  topicId: 'his-world-ww2',
  subject: 'history_geography',
  prompt: 'Ba lực lượng nào là trụ cột trong khối Đồng minh chống phát xít?',
  options: ['Liên Xô - Mỹ - Anh', 'Đức - Italia - Nhật Bản', 'Pháp - Đức - Mỹ', 'Liên Xô - Trung Quốc - Pháp'],
  correctAnswer: 'Liên Xô - Mỹ - Anh',
  explanation: 'Liên Xô, Mỹ và Anh là ba lực lượng trụ cột của khối Đồng minh chống phát xít trong Chiến tranh thế giới thứ hai.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-ww2-16',
  type: 'mcq',
  category: 'history',
  topicId: 'his-world-ww2',
  subject: 'history_geography',
  prompt: 'Hội nghị I-an-ta (Yalta) giữa nguyên thủ ba cường quốc Liên Xô, Mỹ, Anh diễn ra vào thời gian nào?',
  options: ['Tháng 2/1945', 'Tháng 7/1945', 'Tháng 9/1945', 'Tháng 5/1945'],
  correctAnswer: 'Tháng 2/1945',
  explanation: 'Hội nghị I-an-ta được tổ chức từ ngày 4 đến 11/2/1945 nhằm bàn về việc tổ chức lại trật tự thế giới sau chiến tranh.',
  difficulty: 3,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-ww2-17',
  type: 'mcq',
  category: 'history',
  topicId: 'his-world-ww2',
  subject: 'history_geography',
  prompt: 'Văn kiện Nhật Bản đầu hàng chính thức được ký kết vào ngày nào, khép lại Chiến tranh thế giới thứ hai?',
  options: ['2/9/1945', '15/8/1945', '9/5/1945', '6/8/1945'],
  correctAnswer: '2/9/1945',
  explanation: 'Ngày 2/9/1945, đại diện Nhật Bản ký văn kiện đầu hàng chính thức trên chiến hạm Missouri của Mỹ, chấm dứt hoàn toàn Chiến tranh thế giới thứ hai.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-ww2-18',
  type: 'mcq',
  category: 'history',
  topicId: 'his-world-ww2',
  subject: 'history_geography',
  prompt: 'Chiến thắng nào của Hồng quân Liên Xô năm 1941-1942 đã làm phá sản chiến lược "chiến tranh chớp nhoáng" của Hít-le?',
  options: ['Trận Mát-xcơ-va', 'Trận Xta-lin-grát', 'Trận Béc-lin', 'Trận Cuốc-xcơ'],
  correctAnswer: 'Trận Mát-xcơ-va',
  explanation: 'Chiến thắng Mát-xcơ-va (12/1941) của Hồng quân Liên Xô đã làm phá sản kế hoạch "chiến tranh chớp nhoáng" của phát xít Đức.',
  difficulty: 3,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-ww2-19',
  type: 'mcq',
  category: 'history',
  topicId: 'his-world-ww2',
  subject: 'history_geography',
  prompt: 'Hồng quân Liên Xô tiêu diệt hoàn toàn phát xít Đức tại sào huyệt cuối cùng nào vào tháng 4-5/1945?',
  options: ['Béc-lin', 'Mát-xcơ-va', 'Vác-sa-va', 'Pa-ri'],
  correctAnswer: 'Béc-lin',
  explanation: 'Tháng 4-5/1945, Hồng quân Liên Xô tấn công và tiêu diệt phát xít Đức ngay tại sào huyệt cuối cùng là thủ đô Béc-lin.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-ww2-20',
  type: 'mcq',
  category: 'history',
  topicId: 'his-world-ww2',
  subject: 'history_geography',
  prompt: 'Chiến tranh thế giới thứ hai (1939-1945) do những thế lực nào gây ra?',
  options: ['Chủ nghĩa phát xít Đức - Italia - Nhật Bản', 'Các nước Đồng minh', 'Chủ nghĩa thực dân Anh - Pháp', 'Đế quốc Mỹ'],
  correctAnswer: 'Chủ nghĩa phát xít Đức - Italia - Nhật Bản',
  explanation: 'Chiến tranh thế giới thứ hai do các thế lực phát xít Đức, Italia, Nhật Bản gây ra nhằm phân chia lại thế giới.',
  difficulty: 1,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-asia-6',
  type: 'mcq',
  category: 'history',
  topicId: 'his-world-asia-1918',
  subject: 'history_geography',
  prompt: 'Phong trào Ngũ Tứ ở Trung Quốc bùng nổ vào ngày tháng năm nào?',
  options: ['4/5/1919', '1/7/1921', '1/10/1949', '9/2/1930'],
  correctAnswer: '4/5/1919',
  explanation: 'Ngày 4/5/1919, phong trào Ngũ Tứ bùng nổ ở Trung Quốc, mở đầu cao trào cách mạng chống đế quốc và phong kiến.',
  difficulty: 1,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-asia-7',
  type: 'mcq',
  category: 'history',
  topicId: 'his-world-asia-1918',
  subject: 'history_geography',
  prompt: 'Phong trào Ngũ Tứ ở Trung Quốc đánh dấu bước chuyển của cách mạng Trung Quốc từ giai đoạn nào sang giai đoạn nào?',
  options: [
    'Từ cách mạng dân chủ tư sản kiểu cũ sang cách mạng dân chủ tư sản kiểu mới',
    'Từ phong kiến sang tư bản chủ nghĩa',
    'Từ xã hội chủ nghĩa sang tư bản chủ nghĩa',
    'Từ nội chiến sang hòa bình'
  ],
  correctAnswer: 'Từ cách mạng dân chủ tư sản kiểu cũ sang cách mạng dân chủ tư sản kiểu mới',
  explanation: 'Phong trào Ngũ Tứ (1919) đánh dấu bước chuyển của cách mạng Trung Quốc từ cách mạng dân chủ tư sản kiểu cũ sang cách mạng dân chủ tư sản kiểu mới.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-asia-8',
  type: 'mcq',
  category: 'history',
  topicId: 'his-world-asia-1918',
  subject: 'history_geography',
  prompt: 'Đảng Cộng sản Trung Quốc được thành lập vào năm nào?',
  options: ['1921', '1919', '1925', '1930'],
  correctAnswer: '1921',
  explanation: 'Tháng 7/1921, Đảng Cộng sản Trung Quốc được thành lập, đánh dấu bước ngoặt quan trọng của cách mạng Trung Quốc.',
  difficulty: 1,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-asia-9',
  type: 'mcq',
  category: 'history',
  topicId: 'his-world-asia-1918',
  subject: 'history_geography',
  prompt: 'Ai là lãnh tụ của phong trào đấu tranh giành độc lập ở Ấn Độ theo đường lối hòa bình, không sử dụng bạo lực?',
  options: ['Ma-hát-ma Gan-đi (Gandhi)', 'Nê-ru (Nehru)', 'Xu-các-nô', 'Tôn Trung Sơn'],
  correctAnswer: 'Ma-hát-ma Gan-đi (Gandhi)',
  explanation: 'Ma-hát-ma Gan-đi là lãnh tụ Đảng Quốc đại, lãnh đạo phong trào đấu tranh giành độc lập ở Ấn Độ bằng phương pháp hòa bình, bất bạo động.',
  difficulty: 1,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-asia-10',
  type: 'mcq',
  category: 'history',
  topicId: 'his-world-asia-1918',
  subject: 'history_geography',
  prompt: 'Phương pháp đấu tranh chủ yếu mà Gan-đi và Đảng Quốc đại sử dụng để chống thực dân Anh ở Ấn Độ là gì?',
  options: ['Bất bạo động, bất hợp tác', 'Đấu tranh vũ trang', 'Khởi nghĩa toàn quốc', 'Đàm phán quân sự'],
  correctAnswer: 'Bất bạo động, bất hợp tác',
  explanation: 'Gan-đi chủ trương đấu tranh bằng phương pháp hòa bình, bất bạo động và bất hợp tác với chính quyền thực dân Anh.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-asia-11',
  type: 'mcq',
  category: 'history',
  topicId: 'his-world-asia-1918',
  subject: 'history_geography',
  prompt: 'Sau Chiến tranh thế giới thứ nhất, Nhật Bản đẩy mạnh chính sách gì để giải quyết khó khăn kinh tế?',
  options: ['Quân phiệt hóa bộ máy nhà nước, tăng cường xâm lược', 'Cải cách dân chủ tư sản', 'Thực hiện chính sách kinh tế mới', 'Rút khỏi các thuộc địa'],
  correctAnswer: 'Quân phiệt hóa bộ máy nhà nước, tăng cường xâm lược',
  explanation: 'Để thoát khỏi khủng hoảng, giới cầm quyền Nhật Bản chủ trương quân phiệt hóa bộ máy nhà nước, gây chiến tranh xâm lược, thể hiện qua việc xâm lược Mãn Châu năm 1931.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-asia-12',
  type: 'mcq',
  category: 'history',
  topicId: 'his-world-asia-1918',
  subject: 'history_geography',
  prompt: 'Ai là người sáng lập Đảng Dân tộc In-đô-nê-xi-a (PNI) năm 1927, lãnh đạo phong trào đấu tranh giành độc lập?',
  options: ['Xu-các-nô (Sukarno)', 'Gan-đi', 'Tôn Trung Sơn', 'Nguyễn Ái Quốc'],
  correctAnswer: 'Xu-các-nô (Sukarno)',
  explanation: 'Năm 1927, Xu-các-nô sáng lập Đảng Dân tộc In-đô-nê-xi-a (PNI), lãnh đạo phong trào đấu tranh giành độc lập dân tộc ở In-đô-nê-xi-a.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-asia-13',
  type: 'mcq',
  category: 'history',
  topicId: 'his-world-asia-1918',
  subject: 'history_geography',
  prompt: 'Cuộc cách mạng do Mút-xta-pha Kê-man A-ta-tuya lãnh đạo, dẫn đến sự thành lập nước Cộng hòa Thổ Nhĩ Kỳ diễn ra vào năm nào?',
  options: ['1923', '1919', '1930', '1911'],
  correctAnswer: '1923',
  explanation: 'Năm 1923, dưới sự lãnh đạo của Mút-xta-pha Kê-man, nước Cộng hòa Thổ Nhĩ Kỳ được thành lập sau thắng lợi cách mạng.',
  difficulty: 3,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-asia-14',
  type: 'mcq',
  category: 'history',
  topicId: 'his-world-asia-1918',
  subject: 'history_geography',
  prompt: 'Nước Cộng hòa Nhân dân Mông Cổ được thành lập vào năm nào?',
  options: ['1924', '1919', '1930', '1945'],
  correctAnswer: '1924',
  explanation: 'Năm 1924, nước Cộng hòa Nhân dân Mông Cổ được thành lập, là nhà nước dân chủ nhân dân đầu tiên ở châu Á sau Liên Xô.',
  difficulty: 3,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-asia-15',
  type: 'mcq',
  category: 'history',
  topicId: 'his-world-asia-1918',
  subject: 'history_geography',
  prompt: 'Đặc điểm nổi bật của phong trào giải phóng dân tộc ở Đông Nam Á sau Chiến tranh thế giới thứ nhất là gì?',
  options: [
    'Xuất hiện khuynh hướng vô sản song song với khuynh hướng tư sản dân tộc',
    'Chỉ có khuynh hướng phong kiến',
    'Hoàn toàn do các nước đế quốc lãnh đạo',
    'Không có phong trào đấu tranh nào'
  ],
  correctAnswer: 'Xuất hiện khuynh hướng vô sản song song với khuynh hướng tư sản dân tộc',
  explanation: 'Sau Chiến tranh thế giới thứ nhất, phong trào giải phóng dân tộc ở Đông Nam Á phát triển với hai khuynh hướng: tư sản dân tộc và vô sản, trong đó khuynh hướng vô sản ngày càng lớn mạnh.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-colonial-6',
  type: 'mcq',
  category: 'history',
  topicId: 'his-vn-colonial',
  subject: 'history_geography',
  prompt: 'Thực dân Pháp tiến hành chương trình khai thác thuộc địa lần thứ hai ở Đông Dương trong khoảng thời gian nào?',
  options: ['1919-1929', '1897-1914', '1930-1936', '1936-1939'],
  correctAnswer: '1919-1929',
  explanation: 'Sau Chiến tranh thế giới thứ nhất, thực dân Pháp tiến hành chương trình khai thác thuộc địa lần thứ hai ở Đông Dương từ năm 1919 đến 1929.',
  difficulty: 1,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-colonial-7',
  type: 'mcq',
  category: 'history',
  topicId: 'his-vn-colonial',
  subject: 'history_geography',
  prompt: 'Trong chương trình khai thác thuộc địa lần thứ hai, thực dân Pháp tập trung đầu tư vốn nhiều nhất vào ngành nào?',
  options: ['Nông nghiệp (đồn điền cao su) và khai mỏ', 'Công nghiệp nặng', 'Giao thông vận tải', 'Giáo dục'],
  correctAnswer: 'Nông nghiệp (đồn điền cao su) và khai mỏ',
  explanation: 'Pháp tập trung vốn đầu tư chủ yếu vào nông nghiệp (đặc biệt là đồn điền cao su) và khai thác mỏ (chủ yếu là than) để thu lợi nhuận nhanh.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-colonial-8',
  type: 'mcq',
  category: 'history',
  topicId: 'his-vn-colonial',
  subject: 'history_geography',
  prompt: 'Ngân hàng nào giữ vai trò chi phối toàn bộ nền kinh tế Đông Dương trong thời kỳ Pháp khai thác thuộc địa?',
  options: ['Ngân hàng Đông Dương', 'Ngân hàng Nhà nước Việt Nam', 'Ngân hàng Pháp quốc', 'Ngân hàng Trung ương Pháp'],
  correctAnswer: 'Ngân hàng Đông Dương',
  explanation: 'Ngân hàng Đông Dương nắm quyền chỉ huy các ngành kinh tế ở Đông Dương, chi phối toàn bộ nền kinh tế thuộc địa.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-colonial-9',
  type: 'mcq',
  category: 'history',
  topicId: 'his-vn-colonial',
  subject: 'history_geography',
  prompt: 'Giai cấp nào ra đời và ngày càng đông đảo, giữ vai trò quan trọng trong xã hội Việt Nam sau chương trình khai thác thuộc địa lần hai?',
  options: ['Giai cấp công nhân', 'Giai cấp địa chủ', 'Giai cấp nông dân', 'Tầng lớp quý tộc'],
  correctAnswer: 'Giai cấp công nhân',
  explanation: 'Cùng với sự phát triển của các đồn điền, hầm mỏ, nhà máy, giai cấp công nhân Việt Nam ra đời và phát triển nhanh chóng về số lượng.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-colonial-10',
  type: 'mcq',
  category: 'history',
  topicId: 'his-vn-colonial',
  subject: 'history_geography',
  prompt: 'Nguyễn Ái Quốc ra đi tìm đường cứu nước từ bến cảng nào, vào ngày tháng năm nào?',
  options: ['Bến cảng Nhà Rồng, 5/6/1911', 'Bến cảng Hải Phòng, 5/6/1911', 'Bến cảng Nhà Rồng, 6/5/1930', 'Bến cảng Sài Gòn, 19/5/1911'],
  correctAnswer: 'Bến cảng Nhà Rồng, 5/6/1911',
  explanation: 'Ngày 5/6/1911, Nguyễn Tất Thành (Nguyễn Ái Quốc) rời bến cảng Nhà Rồng (Sài Gòn) ra đi tìm đường cứu nước.',
  difficulty: 1,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-colonial-11',
  type: 'mcq',
  category: 'history',
  topicId: 'his-vn-colonial',
  subject: 'history_geography',
  prompt: 'Năm 1919, Nguyễn Ái Quốc đã gửi tới Hội nghị Véc-xai văn kiện nào?',
  options: ['Bản yêu sách của nhân dân An Nam', 'Tuyên ngôn Độc lập', 'Đường Kách mệnh', 'Chính cương vắn tắt'],
  correctAnswer: 'Bản yêu sách của nhân dân An Nam',
  explanation: 'Năm 1919, Nguyễn Ái Quốc gửi tới Hội nghị Véc-xai "Bản yêu sách của nhân dân An Nam" đòi các quyền tự do, dân chủ cho nhân dân Việt Nam.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-colonial-12',
  type: 'mcq',
  category: 'history',
  topicId: 'his-vn-colonial',
  subject: 'history_geography',
  prompt: 'Năm 1920, Nguyễn Ái Quốc đã đọc bản luận cương nào của Lênin, từ đó tìm ra con đường cứu nước đúng đắn?',
  options: [
    'Sơ thảo lần thứ nhất những luận cương về vấn đề dân tộc và thuộc địa',
    'Luận cương chính trị',
    'Tuyên ngôn Đảng Cộng sản',
    'Chính cương vắn tắt'
  ],
  correctAnswer: 'Sơ thảo lần thứ nhất những luận cương về vấn đề dân tộc và thuộc địa',
  explanation: 'Tháng 7/1920, Nguyễn Ái Quốc đọc "Sơ thảo lần thứ nhất những luận cương về vấn đề dân tộc và thuộc địa" của Lênin, từ đó khẳng định con đường giành độc lập dân tộc gắn với chủ nghĩa xã hội.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-colonial-13',
  type: 'mcq',
  category: 'history',
  topicId: 'his-vn-colonial',
  subject: 'history_geography',
  prompt: 'Nguyễn Ái Quốc tham gia sáng lập Đảng Cộng sản Pháp tại Đại hội Tua vào năm nào?',
  options: ['1920', '1919', '1921', '1925'],
  correctAnswer: '1920',
  explanation: 'Tháng 12/1920, tại Đại hội Tua, Nguyễn Ái Quốc bỏ phiếu tán thành gia nhập Quốc tế Cộng sản và tham gia sáng lập Đảng Cộng sản Pháp.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-colonial-14',
  type: 'mcq',
  category: 'history',
  topicId: 'his-vn-colonial',
  subject: 'history_geography',
  prompt: 'Hội Việt Nam Cách mạng Thanh niên được Nguyễn Ái Quốc thành lập ở đâu, vào thời gian nào?',
  options: ['Quảng Châu (Trung Quốc), tháng 6/1925', 'Hương Cảng, tháng 2/1930', 'Pa-ri (Pháp), năm 1921', 'Mátxcơva, năm 1923'],
  correctAnswer: 'Quảng Châu (Trung Quốc), tháng 6/1925',
  explanation: 'Tháng 6/1925, tại Quảng Châu (Trung Quốc), Nguyễn Ái Quốc thành lập Hội Việt Nam Cách mạng Thanh niên nhằm truyền bá chủ nghĩa Mác - Lênin về nước.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-colonial-15',
  type: 'mcq',
  category: 'history',
  topicId: 'his-vn-colonial',
  subject: 'history_geography',
  prompt: 'Cơ quan ngôn luận của Hội Việt Nam Cách mạng Thanh niên là tờ báo nào?',
  options: ['Báo Thanh Niên', 'Báo Tin Tức', 'Báo Dân Chúng', 'Báo Người Cùng Khổ'],
  correctAnswer: 'Báo Thanh Niên',
  explanation: 'Báo Thanh Niên do Nguyễn Ái Quốc sáng lập là cơ quan ngôn luận của Hội Việt Nam Cách mạng Thanh niên, tuyên truyền lý luận cách mạng giải phóng dân tộc.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-colonial-16',
  type: 'mcq',
  category: 'history',
  topicId: 'his-vn-colonial',
  subject: 'history_geography',
  prompt: 'Tác phẩm "Đường Kách mệnh" tập hợp những bài giảng của Nguyễn Ái Quốc được xuất bản vào năm nào?',
  options: ['1927', '1925', '1930', '1920'],
  correctAnswer: '1927',
  explanation: 'Năm 1927, tác phẩm "Đường Kách mệnh" của Nguyễn Ái Quốc được xuất bản, trang bị lý luận cách mạng giải phóng dân tộc cho cán bộ của Hội Việt Nam Cách mạng Thanh niên.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-colonial-17',
  type: 'mcq',
  category: 'history',
  topicId: 'his-vn-colonial',
  subject: 'history_geography',
  prompt: 'Việt Nam Quốc dân Đảng được thành lập vào ngày tháng năm nào, do ai đứng đầu?',
  options: ['25/12/1927, do Nguyễn Thái Học đứng đầu', '3/2/1930, do Trần Phú đứng đầu', '6/1925, do Nguyễn Ái Quốc đứng đầu', '1921, do Phan Bội Châu đứng đầu'],
  correctAnswer: '25/12/1927, do Nguyễn Thái Học đứng đầu',
  explanation: 'Việt Nam Quốc dân Đảng được thành lập ngày 25/12/1927, đại diện cho tư tưởng tư sản dân tộc, do Nguyễn Thái Học đứng đầu.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-colonial-18',
  type: 'mcq',
  category: 'history',
  topicId: 'his-vn-colonial',
  subject: 'history_geography',
  prompt: 'Việt Nam Quốc dân Đảng đã phát động cuộc khởi nghĩa nào vào ngày 9/2/1930, nhưng nhanh chóng thất bại?',
  options: ['Khởi nghĩa Yên Bái', 'Khởi nghĩa Bắc Sơn', 'Khởi nghĩa Nam Kỳ', 'Khởi nghĩa Ba Tơ'],
  correctAnswer: 'Khởi nghĩa Yên Bái',
  explanation: 'Ngày 9/2/1930, Việt Nam Quốc dân Đảng phát động khởi nghĩa Yên Bái nhưng nhanh chóng bị thực dân Pháp đàn áp, thất bại.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-colonial-19',
  type: 'mcq',
  category: 'history',
  topicId: 'his-vn-colonial',
  subject: 'history_geography',
  prompt: 'Tổ chức cách mạng nào ra đời từ sự phân hóa của Việt Nam Cách mạng Đảng (Tân Việt) chịu ảnh hưởng của Hội Việt Nam Cách mạng Thanh niên?',
  options: ['Tân Việt Cách mạng Đảng', 'Việt Nam Quốc dân Đảng', 'Đông Dương Cộng sản Đảng', 'Đảng Lập hiến'],
  correctAnswer: 'Tân Việt Cách mạng Đảng',
  explanation: 'Tân Việt Cách mạng Đảng là tổ chức yêu nước chịu ảnh hưởng của Hội Việt Nam Cách mạng Thanh niên, sau này nhiều đảng viên chuyển sang hoạt động theo khuynh hướng vô sản.',
  difficulty: 3,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-colonial-20',
  type: 'mcq',
  category: 'history',
  topicId: 'his-vn-colonial',
  subject: 'history_geography',
  prompt: 'Từ năm 1923 đến 1924, Nguyễn Ái Quốc đã hoạt động chủ yếu ở những đâu để tiếp tục truyền bá con đường cách mạng vô sản?',
  options: ['Liên Xô và Trung Quốc (Quảng Châu)', 'Anh và Mỹ', 'Nhật Bản và Thái Lan', 'Đức và Italia'],
  correctAnswer: 'Liên Xô và Trung Quốc (Quảng Châu)',
  explanation: 'Năm 1923, Nguyễn Ái Quốc sang Liên Xô dự Hội nghị Quốc tế Nông dân; cuối năm 1924 Người đến Quảng Châu (Trung Quốc) để chuẩn bị thành lập tổ chức cách mạng.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-party-6',
  type: 'mcq',
  category: 'history',
  topicId: 'his-vn-party',
  subject: 'history_geography',
  prompt: 'Đảng Cộng sản Việt Nam được thành lập vào ngày tháng năm nào?',
  options: ['3/2/1930', '9/2/1930', '1/5/1930', '3/2/1931'],
  correctAnswer: '3/2/1930',
  explanation: 'Ngày 3/2/1930, Hội nghị hợp nhất các tổ chức cộng sản họp tại Cửu Long (Hương Cảng, Trung Quốc) đã quyết định thành lập Đảng Cộng sản Việt Nam.',
  difficulty: 1,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-party-7',
  type: 'mcq',
  category: 'history',
  topicId: 'his-vn-party',
  subject: 'history_geography',
  prompt: 'Ai là người chủ trì Hội nghị hợp nhất ba tổ chức cộng sản thành Đảng Cộng sản Việt Nam?',
  options: ['Nguyễn Ái Quốc', 'Trần Phú', 'Lê Hồng Phong', 'Ngô Gia Tự'],
  correctAnswer: 'Nguyễn Ái Quốc',
  explanation: 'Nguyễn Ái Quốc, với tư cách phái viên Quốc tế Cộng sản, đã chủ trì Hội nghị hợp nhất các tổ chức cộng sản thành Đảng Cộng sản Việt Nam ngày 3/2/1930.',
  difficulty: 1,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-party-8',
  type: 'mcq',
  category: 'history',
  topicId: 'his-vn-party',
  subject: 'history_geography',
  prompt: 'Trước khi hợp nhất thành một đảng duy nhất, ở Việt Nam năm 1929 tồn tại bao nhiêu tổ chức cộng sản?',
  options: ['3 tổ chức', '2 tổ chức', '4 tổ chức', '5 tổ chức'],
  correctAnswer: '3 tổ chức',
  explanation: 'Năm 1929, ở Việt Nam lần lượt ra đời ba tổ chức cộng sản: Đông Dương Cộng sản Đảng, An Nam Cộng sản Đảng và Đông Dương Cộng sản Liên đoàn.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-party-9',
  type: 'mcq',
  category: 'history',
  topicId: 'his-vn-party',
  subject: 'history_geography',
  prompt: 'Văn kiện nào do Nguyễn Ái Quốc soạn thảo, được thông qua tại Hội nghị thành lập Đảng, coi là Cương lĩnh chính trị đầu tiên của Đảng?',
  options: ['Chính cương vắn tắt, Sách lược vắn tắt', 'Luận cương chính trị tháng 10/1930', 'Bản yêu sách của nhân dân An Nam', 'Đường Kách mệnh'],
  correctAnswer: 'Chính cương vắn tắt, Sách lược vắn tắt',
  explanation: 'Chính cương vắn tắt và Sách lược vắn tắt do Nguyễn Ái Quốc soạn thảo, được thông qua tại Hội nghị thành lập Đảng, là Cương lĩnh chính trị đầu tiên của Đảng Cộng sản Việt Nam.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-party-10',
  type: 'mcq',
  category: 'history',
  topicId: 'his-vn-party',
  subject: 'history_geography',
  prompt: 'Đảng Cộng sản Việt Nam được đổi tên thành Đảng Cộng sản Đông Dương vào thời gian nào?',
  options: ['10/1930', '3/2/1930', '9/1930', '1931'],
  correctAnswer: '10/1930',
  explanation: 'Tháng 10/1930, Hội nghị lần thứ nhất Ban Chấp hành Trung ương lâm thời quyết định đổi tên Đảng Cộng sản Việt Nam thành Đảng Cộng sản Đông Dương.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-party-11',
  type: 'mcq',
  category: 'history',
  topicId: 'his-vn-party',
  subject: 'history_geography',
  prompt: 'Ai là Tổng Bí thư đầu tiên của Đảng Cộng sản Đông Dương?',
  options: ['Trần Phú', 'Nguyễn Ái Quốc', 'Lê Hồng Phong', 'Hà Huy Tập'],
  correctAnswer: 'Trần Phú',
  explanation: 'Tại Hội nghị lần thứ nhất Ban Chấp hành Trung ương Đảng (10/1930), Trần Phú được bầu làm Tổng Bí thư đầu tiên của Đảng Cộng sản Đông Dương.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-party-12',
  type: 'mcq',
  category: 'history',
  topicId: 'his-vn-party',
  subject: 'history_geography',
  prompt: 'Văn kiện Luận cương chính trị tháng 10/1930 do ai soạn thảo?',
  options: ['Trần Phú', 'Nguyễn Ái Quốc', 'Ngô Gia Tự', 'Nguyễn Đức Cảnh'],
  correctAnswer: 'Trần Phú',
  explanation: 'Trần Phú là người soạn thảo Luận cương chính trị tháng 10/1930, xác định nhiệm vụ cách mạng Đông Dương.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-party-13',
  type: 'mcq',
  category: 'history',
  topicId: 'his-vn-party',
  subject: 'history_geography',
  prompt: 'Phong trào Xô viết Nghệ - Tĩnh diễn ra sôi nổi nhất trong khoảng thời gian nào?',
  options: ['1930-1931', '1928-1929', '1936-1939', '1939-1945'],
  correctAnswer: '1930-1931',
  explanation: 'Phong trào cách mạng 1930-1931 với đỉnh cao là Xô viết Nghệ - Tĩnh diễn ra sôi nổi ở hai tỉnh Nghệ An và Hà Tĩnh.',
  difficulty: 1,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-party-14',
  type: 'mcq',
  category: 'history',
  topicId: 'his-vn-party',
  subject: 'history_geography',
  prompt: 'Sự kiện tiêu biểu nào được coi là đỉnh cao của phong trào cách mạng 1930-1931, diễn ra vào ngày 12/9/1930?',
  options: ['Cuộc biểu tình của nông dân huyện Hưng Nguyên (Nghệ An)', 'Khởi nghĩa Yên Bái', 'Khởi nghĩa Bắc Sơn', 'Cuộc Tổng khởi nghĩa toàn quốc'],
  correctAnswer: 'Cuộc biểu tình của nông dân huyện Hưng Nguyên (Nghệ An)',
  explanation: 'Ngày 12/9/1930, cuộc biểu tình của hàng vạn nông dân huyện Hưng Nguyên (Nghệ An) là đỉnh cao của phong trào Xô viết Nghệ - Tĩnh.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-party-15',
  type: 'mcq',
  category: 'history',
  topicId: 'his-vn-party',
  subject: 'history_geography',
  prompt: 'Chính quyền Xô viết Nghệ - Tĩnh được đánh giá là hình thức chính quyền như thế nào?',
  options: [
    'Hình thức sơ khai của chính quyền công nông, mang tính chất cách mạng triệt để',
    'Chính quyền phong kiến cải cách',
    'Chính quyền tự trị của thực dân Pháp',
    'Chính quyền lâm thời trung lập'
  ],
  correctAnswer: 'Hình thức sơ khai của chính quyền công nông, mang tính chất cách mạng triệt để',
  explanation: 'Xô viết Nghệ - Tĩnh là hình thức sơ khai của chính quyền công nông, đem lại nhiều quyền lợi thiết thực cho nhân dân, thể hiện tính chất cách mạng triệt để.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-party-16',
  type: 'mcq',
  category: 'history',
  topicId: 'his-vn-party',
  subject: 'history_geography',
  prompt: 'Phong trào dân chủ 1936-1939 ở Việt Nam diễn ra trong bối cảnh quốc tế nào?',
  options: [
    'Mặt trận Nhân dân Pháp lên cầm quyền, thi hành một số chính sách tiến bộ ở thuộc địa',
    'Chiến tranh thế giới thứ hai bùng nổ',
    'Nhật đảo chính Pháp ở Đông Dương',
    'Liên Xô tan rã'
  ],
  correctAnswer: 'Mặt trận Nhân dân Pháp lên cầm quyền, thi hành một số chính sách tiến bộ ở thuộc địa',
  explanation: 'Năm 1936, Mặt trận Nhân dân Pháp thắng cử và lên cầm quyền, thi hành một số chính sách tiến bộ, tạo điều kiện cho phong trào dân chủ 1936-1939 ở Đông Dương phát triển.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-party-17',
  type: 'mcq',
  category: 'history',
  topicId: 'his-vn-party',
  subject: 'history_geography',
  prompt: 'Trong phong trào dân chủ 1936-1939, Đảng ta đã thành lập mặt trận nào để tập hợp lực lượng?',
  options: ['Mặt trận Dân chủ Đông Dương', 'Mặt trận Việt Minh', 'Mặt trận Liên Việt', 'Mặt trận Tổ quốc'],
  correctAnswer: 'Mặt trận Dân chủ Đông Dương',
  explanation: 'Năm 1938, Đảng Cộng sản Đông Dương thành lập Mặt trận Dân chủ Đông Dương nhằm tập hợp mọi lực lượng yêu nước, dân chủ, tiến bộ.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-party-18',
  type: 'mcq',
  category: 'history',
  topicId: 'his-vn-party',
  subject: 'history_geography',
  prompt: 'Hai tờ báo công khai nào là cơ quan ngôn luận quan trọng của Đảng trong phong trào dân chủ 1936-1939?',
  options: ['Tin Tức và Dân Chúng', 'Thanh Niên và Người Cùng Khổ', 'Cứu Quốc và Việt Nam Độc Lập', 'Nhân Dân và Cờ Giải Phóng'],
  correctAnswer: 'Tin Tức và Dân Chúng',
  explanation: 'Trong phong trào dân chủ 1936-1939, báo Tin Tức và Dân Chúng là những tờ báo công khai của Đảng, tuyên truyền chủ trương, đường lối cách mạng.',
  difficulty: 3,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-party-19',
  type: 'mcq',
  category: 'history',
  topicId: 'his-vn-party',
  subject: 'history_geography',
  prompt: 'Phong trào Đông Dương Đại hội năm 1936 nhằm mục đích gì?',
  options: [
    'Thu thập nguyện vọng của nhân dân để đòi chính phủ Pháp cải cách dân chủ',
    'Chuẩn bị khởi nghĩa vũ trang giành chính quyền',
    'Thành lập chính phủ lâm thời',
    'Đàm phán trực tiếp với phát xít Nhật'
  ],
  correctAnswer: 'Thu thập nguyện vọng của nhân dân để đòi chính phủ Pháp cải cách dân chủ',
  explanation: 'Phong trào Đông Dương Đại hội năm 1936 nhằm thu thập "dân nguyện" của nhân dân, tập hợp lực lượng đấu tranh đòi các quyền tự do, dân chủ.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-party-20',
  type: 'mcq',
  category: 'history',
  topicId: 'his-vn-party',
  subject: 'history_geography',
  prompt: 'Phong trào dân chủ 1936-1939 kết thúc khi nào và vì sao?',
  options: [
    'Năm 1939, khi Chiến tranh thế giới thứ hai bùng nổ, Pháp tăng cường đàn áp',
    'Năm 1930, khi Đảng Cộng sản Việt Nam ra đời',
    'Năm 1940, khi Nhật vào Đông Dương',
    'Năm 1945, khi Nhật đầu hàng'
  ],
  correctAnswer: 'Năm 1939, khi Chiến tranh thế giới thứ hai bùng nổ, Pháp tăng cường đàn áp',
  explanation: 'Tháng 9/1939, Chiến tranh thế giới thứ hai bùng nổ, thực dân Pháp ở Đông Dương thi hành chính sách thời chiến, đàn áp phong trào cách mạng, chấm dứt phong trào dân chủ 1936-1939.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-aug-6',
  type: 'mcq',
  category: 'history',
  topicId: 'his-vn-aug-revolution',
  subject: 'history_geography',
  prompt: 'Nhật đảo chính Pháp trên toàn cõi Đông Dương vào ngày tháng năm nào?',
  options: ['9/3/1945', '15/8/1945', '2/9/1945', '19/8/1945'],
  correctAnswer: '9/3/1945',
  explanation: 'Đêm 9/3/1945, Nhật Bản tiến hành đảo chính lật đổ Pháp trên toàn cõi Đông Dương để độc chiếm thuộc địa này.',
  difficulty: 1,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-aug-7',
  type: 'mcq',
  category: 'history',
  topicId: 'his-vn-aug-revolution',
  subject: 'history_geography',
  prompt: 'Ngay sau sự kiện Nhật đảo chính Pháp, Ban Thường vụ Trung ương Đảng đã ra chỉ thị nào?',
  options: [
    '"Nhật - Pháp bắn nhau và hành động của chúng ta"',
    '"Toàn dân kháng chiến"',
    '"Kháng chiến kiến quốc"',
    '"Người cày có ruộng"'
  ],
  correctAnswer: '"Nhật - Pháp bắn nhau và hành động của chúng ta"',
  explanation: 'Ngày 12/3/1945, Ban Thường vụ Trung ương Đảng ra chỉ thị "Nhật - Pháp bắn nhau và hành động của chúng ta", phát động cao trào kháng Nhật cứu nước.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-aug-8',
  type: 'mcq',
  category: 'history',
  topicId: 'his-vn-aug-revolution',
  subject: 'history_geography',
  prompt: 'Nạn đói khủng khiếp cuối năm 1944 đầu năm 1945 đã làm bao nhiêu người dân Việt Nam chết đói?',
  options: ['Khoảng 2 triệu người', 'Khoảng 500 nghìn người', 'Khoảng 5 triệu người', 'Khoảng 1 triệu người'],
  correctAnswer: 'Khoảng 2 triệu người',
  explanation: 'Do chính sách vơ vét, bóc lột của Nhật - Pháp, nạn đói cuối 1944 đầu 1945 đã khiến khoảng 2 triệu đồng bào ta chết đói.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-aug-9',
  type: 'mcq',
  category: 'history',
  topicId: 'his-vn-aug-revolution',
  subject: 'history_geography',
  prompt: 'Hội nghị toàn quốc của Đảng quyết định Tổng khởi nghĩa được tổ chức ở đâu, vào thời gian nào?',
  options: ['Tân Trào (Tuyên Quang), 14-15/8/1945', 'Pác Bó (Cao Bằng), 1941', 'Hà Nội, 19/8/1945', 'Huế, 23/8/1945'],
  correctAnswer: 'Tân Trào (Tuyên Quang), 14-15/8/1945',
  explanation: 'Từ ngày 14 đến 15/8/1945, Hội nghị toàn quốc của Đảng họp ở Tân Trào (Tuyên Quang) quyết định phát động Tổng khởi nghĩa trong cả nước.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-aug-10',
  type: 'mcq',
  category: 'history',
  topicId: 'his-vn-aug-revolution',
  subject: 'history_geography',
  prompt: 'Đại hội Quốc dân được tổ chức tại Tân Trào vào ngày 16/8/1945 đã quyết định thành lập cơ quan nào?',
  options: ['Ủy ban Dân tộc giải phóng Việt Nam', 'Chính phủ Cách mạng lâm thời', 'Mặt trận Việt Minh', 'Quân đội Quốc gia Việt Nam'],
  correctAnswer: 'Ủy ban Dân tộc giải phóng Việt Nam',
  explanation: 'Đại hội Quốc dân Tân Trào (16/8/1945) đã bầu ra Ủy ban Dân tộc giải phóng Việt Nam do Hồ Chí Minh làm Chủ tịch.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-aug-11',
  type: 'mcq',
  category: 'history',
  topicId: 'his-vn-aug-revolution',
  subject: 'history_geography',
  prompt: 'Ai được bầu làm Chủ tịch Ủy ban Dân tộc giải phóng Việt Nam tại Đại hội Quốc dân Tân Trào?',
  options: ['Hồ Chí Minh', 'Trường Chinh', 'Võ Nguyên Giáp', 'Phạm Văn Đồng'],
  correctAnswer: 'Hồ Chí Minh',
  explanation: 'Hồ Chí Minh được Đại hội Quốc dân Tân Trào bầu làm Chủ tịch Ủy ban Dân tộc giải phóng Việt Nam.',
  difficulty: 1,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-aug-12',
  type: 'mcq',
  category: 'history',
  topicId: 'his-vn-aug-revolution',
  subject: 'history_geography',
  prompt: 'Cuộc Tổng khởi nghĩa giành chính quyền ở Hà Nội diễn ra thắng lợi vào ngày nào?',
  options: ['19/8/1945', '23/8/1945', '25/8/1945', '2/9/1945'],
  correctAnswer: '19/8/1945',
  explanation: 'Ngày 19/8/1945, cuộc khởi nghĩa giành chính quyền ở Hà Nội giành thắng lợi, tạo tiếng vang lớn thúc đẩy cách mạng cả nước.',
  difficulty: 1,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-aug-13',
  type: 'mcq',
  category: 'history',
  topicId: 'his-vn-aug-revolution',
  subject: 'history_geography',
  prompt: 'Vua Bảo Đại tuyên bố thoái vị, trao ấn kiếm cho chính quyền cách mạng vào ngày nào, tại đâu?',
  options: ['30/8/1945, tại Huế', '19/8/1945, tại Hà Nội', '25/8/1945, tại Sài Gòn', '2/9/1945, tại Hà Nội'],
  correctAnswer: '30/8/1945, tại Huế',
  explanation: 'Ngày 30/8/1945, tại Huế, vua Bảo Đại tuyên bố thoái vị, trao ấn kiếm cho đại diện chính quyền cách mạng, chấm dứt chế độ phong kiến ở Việt Nam.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-aug-14',
  type: 'mcq',
  category: 'history',
  topicId: 'his-vn-aug-revolution',
  subject: 'history_geography',
  prompt: 'Cuộc khởi nghĩa giành chính quyền ở Sài Gòn diễn ra thắng lợi vào ngày nào?',
  options: ['25/8/1945', '19/8/1945', '23/8/1945', '30/8/1945'],
  correctAnswer: '25/8/1945',
  explanation: 'Ngày 25/8/1945, khởi nghĩa giành chính quyền ở Sài Gòn giành thắng lợi, hoàn thành về cơ bản Tổng khởi nghĩa trên cả nước.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-aug-15',
  type: 'mcq',
  category: 'history',
  topicId: 'his-vn-aug-revolution',
  subject: 'history_geography',
  prompt: 'Chủ tịch Hồ Chí Minh đọc bản Tuyên ngôn Độc lập, khai sinh nước Việt Nam Dân chủ Cộng hòa vào ngày nào?',
  options: ['2/9/1945', '19/8/1945', '30/8/1945', '9/3/1945'],
  correctAnswer: '2/9/1945',
  explanation: 'Ngày 2/9/1945, tại Quảng trường Ba Đình (Hà Nội), Chủ tịch Hồ Chí Minh đọc bản Tuyên ngôn Độc lập, khai sinh nước Việt Nam Dân chủ Cộng hòa.',
  difficulty: 1,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-aug-16',
  type: 'mcq',
  category: 'history',
  topicId: 'his-vn-aug-revolution',
  subject: 'history_geography',
  prompt: 'Cách mạng tháng Tám năm 1945 diễn ra và giành thắng lợi trong khoảng thời gian bao lâu?',
  options: ['Khoảng 15 ngày (14-28/8/1945)', 'Khoảng 1 tháng', 'Khoảng 3 tháng', 'Khoảng 1 năm'],
  correctAnswer: 'Khoảng 15 ngày (14-28/8/1945)',
  explanation: 'Cách mạng tháng Tám diễn ra nhanh chóng, từ ngày 14 đến 28/8/1945, chính quyền trong cả nước về tay nhân dân.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-aug-17',
  type: 'mcq',
  category: 'history',
  topicId: 'his-vn-aug-revolution',
  subject: 'history_geography',
  prompt: 'Ủy ban Khởi nghĩa toàn quốc đã ban bố mệnh lệnh nào để phát động Tổng khởi nghĩa trong cả nước?',
  options: ['Quân lệnh số 1', 'Chỉ thị "Nhật - Pháp bắn nhau"', 'Lời kêu gọi toàn quốc kháng chiến', 'Hiệp định sơ bộ'],
  correctAnswer: 'Quân lệnh số 1',
  explanation: 'Đêm 13/8/1945, Ủy ban Khởi nghĩa toàn quốc ra "Quân lệnh số 1", chính thức phát động Tổng khởi nghĩa trong cả nước.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-aug-18',
  type: 'mcq',
  category: 'history',
  topicId: 'his-vn-aug-revolution',
  subject: 'history_geography',
  prompt: 'Điều kiện khách quan thuận lợi nào đã tạo thời cơ cho Tổng khởi nghĩa tháng Tám năm 1945 bùng nổ?',
  options: ['Phát xít Nhật đầu hàng Đồng minh không điều kiện', 'Pháp quay lại xâm lược Việt Nam', 'Mỹ đổ bộ vào Việt Nam', 'Trung Quốc tuyên chiến với Nhật'],
  correctAnswer: 'Phát xít Nhật đầu hàng Đồng minh không điều kiện',
  explanation: 'Ngày 15/8/1945, phát xít Nhật đầu hàng Đồng minh không điều kiện, quân Nhật ở Đông Dương tan rã, tạo thời cơ "ngàn năm có một" để nhân dân ta Tổng khởi nghĩa.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-aug-19',
  type: 'mcq',
  category: 'history',
  topicId: 'his-vn-aug-revolution',
  subject: 'history_geography',
  prompt: 'Khởi nghĩa giành chính quyền ở Huế diễn ra thắng lợi vào ngày nào?',
  options: ['23/8/1945', '19/8/1945', '25/8/1945', '30/8/1945'],
  correctAnswer: '23/8/1945',
  explanation: 'Ngày 23/8/1945, khởi nghĩa giành chính quyền ở Huế - kinh đô của triều đình phong kiến - giành thắng lợi.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-his-aug-20',
  type: 'mcq',
  category: 'history',
  topicId: 'his-vn-aug-revolution',
  subject: 'history_geography',
  prompt: 'Nguyên nhân chủ quan quyết định thắng lợi của Cách mạng tháng Tám năm 1945 là gì?',
  options: [
    'Sự lãnh đạo đúng đắn, sáng suốt của Đảng Cộng sản Đông Dương và Chủ tịch Hồ Chí Minh',
    'Phát xít Nhật đầu hàng Đồng minh',
    'Sự giúp đỡ của quân Đồng minh',
    'Thực dân Pháp suy yếu'
  ],
  correctAnswer: 'Sự lãnh đạo đúng đắn, sáng suốt của Đảng Cộng sản Đông Dương và Chủ tịch Hồ Chí Minh',
  explanation: 'Nguyên nhân chủ quan quyết định thắng lợi của Cách mạng tháng Tám là sự lãnh đạo đúng đắn, sáng tạo của Đảng và Chủ tịch Hồ Chí Minh, cùng truyền thống yêu nước của dân tộc.',
  difficulty: 2,
  source: 'GDPT 2018 - Lịch sử lớp 9'
},
{
  id: 'gk-geo-population-6',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-population',
  subject: 'history_geography',
  prompt: 'Việt Nam là quốc gia có bao nhiêu dân tộc anh em cùng sinh sống?',
  options: ['54 dân tộc', '45 dân tộc', '63 dân tộc', '36 dân tộc'],
  correctAnswer: '54 dân tộc',
  explanation: 'Việt Nam có 54 dân tộc anh em cùng sinh sống, trong đó dân tộc Kinh (Việt) chiếm đa số.',
  difficulty: 1,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-population-7',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-population',
  subject: 'history_geography',
  prompt: 'Dân tộc nào chiếm tỉ lệ đa số trong cơ cấu dân số Việt Nam?',
  options: ['Dân tộc Kinh (Việt)', 'Dân tộc Tày', 'Dân tộc Thái', 'Dân tộc Mường'],
  correctAnswer: 'Dân tộc Kinh (Việt)',
  explanation: 'Dân tộc Kinh (Việt) chiếm khoảng 85% dân số cả nước, phân bố chủ yếu ở đồng bằng, ven biển và trung du.',
  difficulty: 1,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-population-8',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-population',
  subject: 'history_geography',
  prompt: 'Các dân tộc ít người ở Việt Nam thường sinh sống tập trung chủ yếu ở đâu?',
  options: ['Miền núi và trung du', 'Đồng bằng sông Hồng', 'Các đô thị lớn', 'Ven biển'],
  correctAnswer: 'Miền núi và trung du',
  explanation: 'Các dân tộc ít người chủ yếu cư trú ở miền núi và trung du, chiếm khoảng 2/3 diện tích lãnh thổ cả nước.',
  difficulty: 1,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-population-9',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-population',
  subject: 'history_geography',
  prompt: 'Vùng nào có mật độ dân số cao nhất cả nước?',
  options: ['Đồng bằng sông Hồng', 'Tây Nguyên', 'Trung du miền núi phía Bắc', 'Duyên hải Nam Trung Bộ'],
  correctAnswer: 'Đồng bằng sông Hồng',
  explanation: 'Đồng bằng sông Hồng là vùng có mật độ dân số cao nhất cả nước do điều kiện tự nhiên thuận lợi và lịch sử khai thác lâu đời.',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-population-10',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-population',
  subject: 'history_geography',
  prompt: '"Cơ cấu dân số vàng" là khái niệm chỉ điều gì?',
  options: [
    'Nhóm dân số trong độ tuổi lao động chiếm tỉ lệ cao gấp hơn hai lần nhóm dân số phụ thuộc',
    'Dân số có thu nhập cao',
    'Dân số đô thị chiếm ưu thế',
    'Dân số nữ nhiều hơn dân số nam'
  ],
  correctAnswer: 'Nhóm dân số trong độ tuổi lao động chiếm tỉ lệ cao gấp hơn hai lần nhóm dân số phụ thuộc',
  explanation: 'Cơ cấu dân số vàng là thời kỳ mà nhóm dân số trong độ tuổi lao động (15-64 tuổi) chiếm tỉ lệ cao, gấp hơn hai lần nhóm dân số phụ thuộc (dưới 15 và trên 64 tuổi).',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-population-11',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-population',
  subject: 'history_geography',
  prompt: 'Việt Nam bước vào thời kỳ cơ cấu dân số vàng bắt đầu từ khoảng năm nào?',
  options: ['2007', '1990', '2015', '2020'],
  correctAnswer: '2007',
  explanation: 'Theo các nghiên cứu dân số, Việt Nam bước vào thời kỳ cơ cấu dân số vàng từ khoảng năm 2007, mang lại nguồn lao động dồi dào cho phát triển kinh tế.',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-population-12',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-population',
  subject: 'history_geography',
  prompt: 'Xu hướng nào đang diễn ra song song với thời kỳ dân số vàng ở Việt Nam hiện nay?',
  options: ['Già hóa dân số', 'Bùng nổ dân số', 'Giảm mạnh tỉ lệ đô thị hóa', 'Tăng nhanh tỉ suất sinh'],
  correctAnswer: 'Già hóa dân số',
  explanation: 'Cùng với thời kỳ dân số vàng, Việt Nam đang đối mặt với xu hướng già hóa dân số do tỉ lệ người từ 65 tuổi trở lên tăng nhanh.',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-population-13',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-population',
  subject: 'history_geography',
  prompt: 'Tỉ lệ dân số thành thị của Việt Nam trong những năm gần đây có xu hướng như thế nào?',
  options: ['Tăng dần theo quá trình đô thị hóa', 'Giảm dần', 'Không thay đổi', 'Giảm mạnh do di dân ra nông thôn'],
  correctAnswer: 'Tăng dần theo quá trình đô thị hóa',
  explanation: 'Cùng với quá trình công nghiệp hóa, hiện đại hóa, tỉ lệ dân số thành thị của Việt Nam ngày càng tăng, tuy vẫn thấp hơn tỉ lệ dân số nông thôn.',
  difficulty: 1,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-population-14',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-population',
  subject: 'history_geography',
  prompt: 'Vấn đề nào đang tồn tại trong cơ cấu dân số theo giới tính ở Việt Nam hiện nay?',
  options: ['Mất cân bằng giới tính khi sinh (thừa nam, thiếu nữ)', 'Thiếu nam giới nghiêm trọng', 'Tỉ số giới tính hoàn toàn cân bằng', 'Dân số nữ giảm mạnh'],
  correctAnswer: 'Mất cân bằng giới tính khi sinh (thừa nam, thiếu nữ)',
  explanation: 'Việt Nam đang gặp tình trạng mất cân bằng giới tính khi sinh, số bé trai sinh ra cao hơn đáng kể so với bé gái so với mức cân bằng tự nhiên.',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-population-15',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-population',
  subject: 'history_geography',
  prompt: 'Sự phân bố dân cư của Việt Nam có đặc điểm nổi bật nào?',
  options: [
    'Không đồng đều giữa đồng bằng và miền núi, giữa thành thị và nông thôn',
    'Đồng đều tuyệt đối trên toàn lãnh thổ',
    'Tập trung chủ yếu ở miền núi',
    'Chủ yếu phân bố ở khu vực biên giới'
  ],
  correctAnswer: 'Không đồng đều giữa đồng bằng và miền núi, giữa thành thị và nông thôn',
  explanation: 'Dân cư Việt Nam phân bố không đều: tập trung đông ở đồng bằng, ven biển, đô thị; thưa thớt ở miền núi, biên giới, hải đảo.',
  difficulty: 1,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-population-16',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-population',
  subject: 'history_geography',
  prompt: 'Nhóm dân tộc nào sau đây thuộc nhóm các dân tộc ít người có số dân đông ở Việt Nam?',
  options: ['Tày, Thái, Mường', 'Kinh, Chăm, Hoa', 'Ê-đê, Gia-rai, Ba-na', 'Khơ-me, Chăm, Hoa'],
  correctAnswer: 'Tày, Thái, Mường',
  explanation: 'Tày, Thái, Mường là ba trong số các dân tộc ít người có số dân đông nhất Việt Nam, chủ yếu cư trú ở miền núi phía Bắc.',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-population-17',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-population',
  subject: 'history_geography',
  prompt: 'Dân tộc Khơ-me và dân tộc Chăm chủ yếu phân bố ở khu vực nào của Việt Nam?',
  options: ['Nam Bộ và Duyên hải Nam Trung Bộ', 'Trung du miền núi phía Bắc', 'Đồng bằng sông Hồng', 'Bắc Trung Bộ'],
  correctAnswer: 'Nam Bộ và Duyên hải Nam Trung Bộ',
  explanation: 'Dân tộc Khơ-me sinh sống chủ yếu ở Nam Bộ (Đồng bằng sông Cửu Long), còn dân tộc Chăm phân bố chủ yếu ở Duyên hải Nam Trung Bộ.',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-population-18',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-population',
  subject: 'history_geography',
  prompt: 'Việc phân bố dân cư không đồng đều gây ra khó khăn gì cho phát triển kinh tế - xã hội?',
  options: [
    'Gây sức ép lên tài nguyên, môi trường ở nơi đông dân; thiếu lao động ở nơi thưa dân',
    'Không ảnh hưởng gì đến phát triển kinh tế',
    'Chỉ ảnh hưởng đến giáo dục',
    'Giúp phân bố tài nguyên đồng đều hơn'
  ],
  correctAnswer: 'Gây sức ép lên tài nguyên, môi trường ở nơi đông dân; thiếu lao động ở nơi thưa dân',
  explanation: 'Phân bố dân cư không đồng đều gây sức ép về việc làm, tài nguyên, môi trường ở vùng đông dân; trong khi vùng thưa dân lại thiếu lao động khai thác tiềm năng.',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-population-19',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-population',
  subject: 'history_geography',
  prompt: 'Dân số Việt Nam theo Tổng cục Thống kê đạt khoảng bao nhiêu triệu người vào các năm gần đây (đầu thập niên 2020)?',
  options: ['Khoảng 100 triệu người', 'Khoảng 50 triệu người', 'Khoảng 150 triệu người', 'Khoảng 200 triệu người'],
  correctAnswer: 'Khoảng 100 triệu người',
  explanation: 'Dân số Việt Nam đạt mốc khoảng 100 triệu người vào đầu những năm 2020, đứng trong nhóm các quốc gia đông dân trên thế giới.',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-population-20',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-population',
  subject: 'history_geography',
  prompt: 'Chính sách dân số - kế hoạch hóa gia đình ở Việt Nam nhằm mục tiêu chủ yếu gì?',
  options: [
    'Giảm tỉ lệ gia tăng dân số tự nhiên, nâng cao chất lượng dân số',
    'Tăng nhanh tỉ lệ sinh',
    'Khuyến khích di dân tự do',
    'Giảm số lượng dân tộc ít người'
  ],
  correctAnswer: 'Giảm tỉ lệ gia tăng dân số tự nhiên, nâng cao chất lượng dân số',
  explanation: 'Chính sách dân số - kế hoạch hóa gia đình nhằm giảm tỉ lệ gia tăng dân số tự nhiên và nâng cao chất lượng dân số, phù hợp với phát triển kinh tế - xã hội.',
  difficulty: 1,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-agri-6',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-agri-forestry-fish',
  subject: 'history_geography',
  prompt: 'Vùng nào là vựa lúa lớn nhất cả nước, chiếm khoảng 50% sản lượng lúa của Việt Nam?',
  options: ['Đồng bằng sông Cửu Long', 'Đồng bằng sông Hồng', 'Tây Nguyên', 'Bắc Trung Bộ'],
  correctAnswer: 'Đồng bằng sông Cửu Long',
  explanation: 'Đồng bằng sông Cửu Long là vựa lúa lớn nhất cả nước, chiếm khoảng 50% sản lượng lúa và là vùng xuất khẩu gạo chủ lực của Việt Nam.',
  difficulty: 1,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-agri-7',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-agri-forestry-fish',
  subject: 'history_geography',
  prompt: 'Vùng nào là vùng trồng cà phê lớn nhất cả nước?',
  options: ['Tây Nguyên', 'Đông Nam Bộ', 'Trung du miền núi phía Bắc', 'Đồng bằng sông Hồng'],
  correctAnswer: 'Tây Nguyên',
  explanation: 'Tây Nguyên là vùng trồng cà phê lớn nhất cả nước nhờ đất badan màu mỡ và khí hậu cao nguyên thích hợp.',
  difficulty: 1,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-agri-8',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-agri-forestry-fish',
  subject: 'history_geography',
  prompt: 'Loại đất chủ yếu ở Tây Nguyên, rất thích hợp để trồng cây công nghiệp lâu năm như cà phê là loại đất gì?',
  options: ['Đất badan (đất đỏ badan)', 'Đất phù sa', 'Đất phèn', 'Đất cát ven biển'],
  correctAnswer: 'Đất badan (đất đỏ badan)',
  explanation: 'Đất badan màu mỡ, tầng phong hóa sâu là loại đất chủ yếu ở Tây Nguyên, rất thích hợp để phát triển cây công nghiệp lâu năm như cà phê, cao su, hồ tiêu.',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-agri-9',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-agri-forestry-fish',
  subject: 'history_geography',
  prompt: 'Việt Nam hiện là quốc gia xuất khẩu cà phê đứng thứ mấy trên thế giới?',
  options: ['Thứ 2', 'Thứ nhất', 'Thứ 5', 'Thứ 10'],
  correctAnswer: 'Thứ 2',
  explanation: 'Việt Nam là quốc gia xuất khẩu cà phê lớn thứ hai thế giới, chỉ sau Bra-xin, với vùng sản xuất chủ lực là Tây Nguyên.',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-agri-10',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-agri-forestry-fish',
  subject: 'history_geography',
  prompt: 'Ngành thủy sản Việt Nam gồm hai hoạt động chính nào?',
  options: ['Đánh bắt và nuôi trồng', 'Chế biến và xuất khẩu', 'Đóng tàu và sửa chữa', 'Khai thác và bảo tồn'],
  correctAnswer: 'Đánh bắt và nuôi trồng',
  explanation: 'Ngành thủy sản Việt Nam gồm hai hoạt động chính là đánh bắt (khai thác) thủy sản tự nhiên và nuôi trồng thủy sản.',
  difficulty: 1,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-agri-11',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-agri-forestry-fish',
  subject: 'history_geography',
  prompt: 'Vùng nào dẫn đầu cả nước về nuôi trồng thủy sản, đặc biệt là tôm và cá tra?',
  options: ['Đồng bằng sông Cửu Long', 'Đồng bằng sông Hồng', 'Tây Nguyên', 'Trung du miền núi phía Bắc'],
  correctAnswer: 'Đồng bằng sông Cửu Long',
  explanation: 'Đồng bằng sông Cửu Long với hệ thống sông ngòi, kênh rạch chằng chịt là vùng dẫn đầu cả nước về nuôi trồng thủy sản, đặc biệt là tôm và cá tra xuất khẩu.',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-agri-12',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-agri-forestry-fish',
  subject: 'history_geography',
  prompt: 'Rừng Việt Nam được phân thành mấy loại theo chức năng sử dụng?',
  options: ['3 loại: rừng phòng hộ, rừng đặc dụng, rừng sản xuất', '2 loại: rừng tự nhiên và rừng trồng', '4 loại', '5 loại'],
  correctAnswer: '3 loại: rừng phòng hộ, rừng đặc dụng, rừng sản xuất',
  explanation: 'Theo chức năng, rừng Việt Nam được chia thành 3 loại: rừng phòng hộ, rừng đặc dụng và rừng sản xuất.',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-agri-13',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-agri-forestry-fish',
  subject: 'history_geography',
  prompt: 'Loại rừng nào có chức năng bảo vệ nguồn nước, chống xói mòn, hạn chế thiên tai?',
  options: ['Rừng phòng hộ', 'Rừng sản xuất', 'Rừng đặc dụng', 'Rừng ngập mặn kinh tế'],
  correctAnswer: 'Rừng phòng hộ',
  explanation: 'Rừng phòng hộ có chức năng bảo vệ nguồn nước, bảo vệ đất, chống xói mòn, hạn chế thiên tai, điều hòa khí hậu.',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-agri-14',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-agri-forestry-fish',
  subject: 'history_geography',
  prompt: 'Rừng đặc dụng có mục đích chủ yếu nào sau đây?',
  options: [
    'Bảo tồn thiên nhiên, các hệ sinh thái, nguồn gen sinh vật, di tích lịch sử - văn hóa',
    'Khai thác gỗ để xuất khẩu',
    'Trồng cây công nghiệp lâu năm',
    'Phát triển đô thị'
  ],
  correctAnswer: 'Bảo tồn thiên nhiên, các hệ sinh thái, nguồn gen sinh vật, di tích lịch sử - văn hóa',
  explanation: 'Rừng đặc dụng (như vườn quốc gia, khu bảo tồn thiên nhiên) có mục đích bảo tồn thiên nhiên, hệ sinh thái, nguồn gen sinh vật và các giá trị văn hóa, lịch sử, du lịch.',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-agri-15',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-agri-forestry-fish',
  subject: 'history_geography',
  prompt: 'Nông nghiệp xanh là mô hình sản xuất nông nghiệp hướng tới mục tiêu nào?',
  options: [
    'Phát triển bền vững, giảm sử dụng hóa chất, bảo vệ môi trường',
    'Tăng tối đa sản lượng bằng mọi giá',
    'Chỉ sản xuất để xuất khẩu',
    'Loại bỏ hoàn toàn cơ giới hóa'
  ],
  correctAnswer: 'Phát triển bền vững, giảm sử dụng hóa chất, bảo vệ môi trường',
  explanation: 'Nông nghiệp xanh hướng đến phát triển bền vững, giảm sử dụng phân bón hóa học, thuốc bảo vệ thực vật, bảo vệ môi trường và sức khỏe con người.',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-agri-16',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-agri-forestry-fish',
  subject: 'history_geography',
  prompt: 'Việt Nam nằm trong nhóm các nước xuất khẩu gạo hàng đầu thế giới, đứng ở vị trí nào?',
  options: ['Trong nhóm 3 nước xuất khẩu gạo lớn nhất thế giới', 'Đứng thứ 10', 'Không xuất khẩu gạo', 'Chỉ nhập khẩu gạo'],
  correctAnswer: 'Trong nhóm 3 nước xuất khẩu gạo lớn nhất thế giới',
  explanation: 'Việt Nam thường xuyên nằm trong nhóm 3 quốc gia xuất khẩu gạo lớn nhất thế giới, cùng với Ấn Độ và Thái Lan.',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-agri-17',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-agri-forestry-fish',
  subject: 'history_geography',
  prompt: 'Ngư trường trọng điểm nào sau đây nằm ở khu vực phía Nam đất nước?',
  options: ['Ngư trường Cà Mau - Kiên Giang', 'Ngư trường Hải Phòng - Quảng Ninh', 'Ngư trường Hoàng Sa - Trường Sa', 'Ngư trường Bắc Bộ'],
  correctAnswer: 'Ngư trường Cà Mau - Kiên Giang',
  explanation: 'Ngư trường Cà Mau - Kiên Giang là một trong bốn ngư trường trọng điểm của Việt Nam, nằm ở khu vực phía Nam, có trữ lượng hải sản lớn.',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-agri-18',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-agri-forestry-fish',
  subject: 'history_geography',
  prompt: 'Vùng nào là vựa lúa lớn thứ hai của cả nước, sau Đồng bằng sông Cửu Long?',
  options: ['Đồng bằng sông Hồng', 'Tây Nguyên', 'Đông Nam Bộ', 'Duyên hải Nam Trung Bộ'],
  correctAnswer: 'Đồng bằng sông Hồng',
  explanation: 'Đồng bằng sông Hồng là vựa lúa lớn thứ hai cả nước, đóng vai trò quan trọng trong an ninh lương thực khu vực phía Bắc.',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-agri-19',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-agri-forestry-fish',
  subject: 'history_geography',
  prompt: 'Ngoài cà phê, Tây Nguyên còn nổi tiếng với các cây công nghiệp lâu năm nào khác?',
  options: ['Cao su, hồ tiêu, chè', 'Lúa nước, ngô, khoai', 'Dừa, mía', 'Thuốc lá, bông'],
  correctAnswer: 'Cao su, hồ tiêu, chè',
  explanation: 'Bên cạnh cà phê, Tây Nguyên còn là vùng chuyên canh các cây công nghiệp lâu năm khác như cao su, hồ tiêu và chè.',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-agri-20',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-agri-forestry-fish',
  subject: 'history_geography',
  prompt: 'Tỉ lệ độ che phủ rừng của Việt Nam hiện nay ở khoảng bao nhiêu phần trăm?',
  options: ['Khoảng 42%', 'Khoảng 10%', 'Khoảng 70%', 'Khoảng 25%'],
  correctAnswer: 'Khoảng 42%',
  explanation: 'Độ che phủ rừng của Việt Nam hiện đạt khoảng 42%, là kết quả của các chương trình trồng rừng và bảo vệ rừng trong nhiều năm qua.',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-industry-6',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-industry',
  subject: 'history_geography',
  prompt: 'Vùng nào được xem là trung tâm công nghiệp lớn nhất và phát triển nhất cả nước?',
  options: ['Đông Nam Bộ', 'Trung du miền núi phía Bắc', 'Tây Nguyên', 'Bắc Trung Bộ'],
  correctAnswer: 'Đông Nam Bộ',
  explanation: 'Đông Nam Bộ (với TP. Hồ Chí Minh, Bình Dương, Đồng Nai, Bà Rịa - Vũng Tàu) là vùng công nghiệp phát triển nhất và có giá trị sản xuất công nghiệp lớn nhất cả nước.',
  difficulty: 1,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-industry-7',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-industry',
  subject: 'history_geography',
  prompt: 'Tỉnh/thành nào là vùng khai thác than đá lớn nhất cả nước?',
  options: ['Quảng Ninh', 'Thanh Hóa', 'Lâm Đồng', 'Bà Rịa - Vũng Tàu'],
  correctAnswer: 'Quảng Ninh',
  explanation: 'Quảng Ninh là vùng có trữ lượng và sản lượng khai thác than đá lớn nhất cả nước, chiếm phần lớn sản lượng than của Việt Nam.',
  difficulty: 1,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-industry-8',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-industry',
  subject: 'history_geography',
  prompt: 'Ngành công nghiệp điện tử của Việt Nam phát triển mạnh nhờ sự đầu tư của các tập đoàn lớn tại các tỉnh nào?',
  options: ['Bắc Ninh, Thái Nguyên', 'Cà Mau, Kiên Giang', 'Lâm Đồng, Đắk Lắk', 'Quảng Nam, Quảng Ngãi'],
  correctAnswer: 'Bắc Ninh, Thái Nguyên',
  explanation: 'Bắc Ninh và Thái Nguyên là hai địa phương thu hút đầu tư lớn của các tập đoàn điện tử (như Samsung), trở thành trung tâm sản xuất điện tử hàng đầu cả nước.',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-industry-9',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-industry',
  subject: 'history_geography',
  prompt: 'Công nghiệp xanh trong phát triển công nghiệp Việt Nam hướng tới mục tiêu nào?',
  options: [
    'Giảm phát thải, sử dụng năng lượng tái tạo, thân thiện môi trường',
    'Tăng tối đa sản lượng khai thác than',
    'Loại bỏ hoàn toàn công nghiệp nặng',
    'Chỉ phát triển công nghiệp nhẹ'
  ],
  correctAnswer: 'Giảm phát thải, sử dụng năng lượng tái tạo, thân thiện môi trường',
  explanation: 'Công nghiệp xanh hướng tới giảm phát thải khí nhà kính, tăng cường sử dụng năng lượng tái tạo và công nghệ sản xuất thân thiện với môi trường.',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-industry-10',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-industry',
  subject: 'history_geography',
  prompt: 'Chuyển đổi số trong công nghiệp Việt Nam gắn liền với xu hướng công nghiệp nào của thế giới?',
  options: ['Cách mạng công nghiệp 4.0', 'Cách mạng công nghiệp lần thứ nhất', 'Cách mạng công nghiệp lần thứ hai', 'Cách mạng xanh'],
  correctAnswer: 'Cách mạng công nghiệp 4.0',
  explanation: 'Chuyển đổi số trong công nghiệp gắn liền với Cách mạng công nghiệp 4.0, ứng dụng công nghệ số, tự động hóa, trí tuệ nhân tạo vào sản xuất.',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-industry-11',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-industry',
  subject: 'history_geography',
  prompt: 'Tỉnh nào của Việt Nam nổi bật với ngành công nghiệp khai thác và chế biến dầu khí?',
  options: ['Bà Rịa - Vũng Tàu', 'Quảng Ninh', 'Lâm Đồng', 'Sơn La'],
  correctAnswer: 'Bà Rịa - Vũng Tàu',
  explanation: 'Bà Rịa - Vũng Tàu là trung tâm khai thác, chế biến dầu khí quan trọng nhất cả nước nhờ vị trí gần các mỏ dầu khí ở thềm lục địa phía Nam.',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-industry-12',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-industry',
  subject: 'history_geography',
  prompt: 'Nhà máy thủy điện Hòa Bình và Sơn La nằm trên hệ thống sông nào?',
  options: ['Sông Đà', 'Sông Hồng', 'Sông Mã', 'Sông Cả'],
  correctAnswer: 'Sông Đà',
  explanation: 'Các nhà máy thủy điện lớn như Hòa Bình và Sơn La được xây dựng trên sông Đà, khai thác tiềm năng thủy điện lớn của vùng Tây Bắc.',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-industry-13',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-industry',
  subject: 'history_geography',
  prompt: 'Khu vực nào của Việt Nam có tiềm năng phát triển điện gió lớn, nổi bật là các tỉnh nào?',
  options: ['Ninh Thuận, Bình Thuận', 'Lào Cai, Yên Bái', 'Bắc Ninh, Hải Dương', 'Cà Mau, Bạc Liêu (chỉ riêng)'],
  correctAnswer: 'Ninh Thuận, Bình Thuận',
  explanation: 'Ninh Thuận và Bình Thuận là hai tỉnh có tiềm năng gió lớn nhất cả nước, phát triển mạnh các dự án điện gió trong những năm gần đây.',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-industry-14',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-industry',
  subject: 'history_geography',
  prompt: 'Khu liên hợp gang thép Formosa, một trong những cơ sở sản xuất thép lớn nhất cả nước, đặt tại tỉnh nào?',
  options: ['Hà Tĩnh', 'Thái Nguyên', 'Quảng Ninh', 'Bà Rịa - Vũng Tàu'],
  correctAnswer: 'Hà Tĩnh',
  explanation: 'Khu liên hợp gang thép Formosa Hà Tĩnh là một trong những cơ sở sản xuất thép quy mô lớn nhất cả nước, đặt tại Khu kinh tế Vũng Áng, tỉnh Hà Tĩnh.',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-industry-15',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-industry',
  subject: 'history_geography',
  prompt: 'Các khu công nghiệp, khu chế xuất của Việt Nam tập trung nhiều nhất ở hai vùng kinh tế nào?',
  options: ['Đông Nam Bộ và Đồng bằng sông Hồng', 'Tây Nguyên và Bắc Trung Bộ', 'Trung du miền núi phía Bắc và Tây Nguyên', 'Duyên hải Nam Trung Bộ và Tây Nguyên'],
  correctAnswer: 'Đông Nam Bộ và Đồng bằng sông Hồng',
  explanation: 'Đông Nam Bộ và Đồng bằng sông Hồng là hai vùng tập trung nhiều khu công nghiệp, khu chế xuất nhất cả nước nhờ hạ tầng phát triển và vị trí thuận lợi.',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-industry-16',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-industry',
  subject: 'history_geography',
  prompt: 'Ngành công nghiệp nào là một trong những ngành xuất khẩu chủ lực truyền thống của Việt Nam bên cạnh điện tử?',
  options: ['Dệt may và da giày', 'Khai thác than', 'Đóng tàu biển', 'Sản xuất ô tô'],
  correctAnswer: 'Dệt may và da giày',
  explanation: 'Dệt may và da giày là hai ngành công nghiệp xuất khẩu chủ lực truyền thống, sử dụng nhiều lao động, đóng góp lớn vào kim ngạch xuất khẩu của Việt Nam.',
  difficulty: 1,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-industry-17',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-industry',
  subject: 'history_geography',
  prompt: 'Vì sao Đông Nam Bộ trở thành vùng công nghiệp phát triển nhất cả nước?',
  options: [
    'Có vị trí địa lí thuận lợi, hạ tầng phát triển, nguồn lao động và vốn đầu tư dồi dào',
    'Chỉ vì có nhiều tài nguyên khoáng sản',
    'Vì có khí hậu lạnh quanh năm',
    'Vì dân số ít, đất đai rộng'
  ],
  correctAnswer: 'Có vị trí địa lí thuận lợi, hạ tầng phát triển, nguồn lao động và vốn đầu tư dồi dào',
  explanation: 'Đông Nam Bộ có vị trí địa lí thuận lợi, cơ sở hạ tầng phát triển, thu hút vốn đầu tư trong và ngoài nước lớn, nguồn lao động dồi dào và có tay nghề.',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-industry-18',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-industry',
  subject: 'history_geography',
  prompt: 'Năng lượng tái tạo nào sau đây đang được đẩy mạnh phát triển ở Việt Nam nhằm hướng đến công nghiệp xanh?',
  options: ['Điện gió và điện mặt trời', 'Điện than', 'Điện hạt nhân', 'Điện dầu diesel'],
  correctAnswer: 'Điện gió và điện mặt trời',
  explanation: 'Điện gió và điện mặt trời là hai loại năng lượng tái tạo đang được đẩy mạnh phát triển ở Việt Nam nhằm giảm phát thải và hướng đến công nghiệp xanh, bền vững.',
  difficulty: 1,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-industry-19',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-industry',
  subject: 'history_geography',
  prompt: 'Thành phố nào được xem là trung tâm công nghiệp lớn nhất cả nước hiện nay?',
  options: ['Thành phố Hồ Chí Minh', 'Hà Nội', 'Đà Nẵng', 'Hải Phòng'],
  correctAnswer: 'Thành phố Hồ Chí Minh',
  explanation: 'Thành phố Hồ Chí Minh là trung tâm công nghiệp, kinh tế lớn nhất cả nước, đóng góp tỉ trọng lớn vào giá trị sản xuất công nghiệp quốc gia.',
  difficulty: 1,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-industry-20',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-industry',
  subject: 'history_geography',
  prompt: 'Chuyển đổi số được ứng dụng trong công nghiệp Việt Nam thông qua công nghệ nào sau đây?',
  options: ['Tự động hóa, trí tuệ nhân tạo, internet vạn vật (IoT)', 'Chỉ máy móc cơ khí truyền thống', 'Lao động thủ công', 'Chỉ sử dụng sức nước'],
  correctAnswer: 'Tự động hóa, trí tuệ nhân tạo, internet vạn vật (IoT)',
  explanation: 'Chuyển đổi số trong công nghiệp ứng dụng các công nghệ hiện đại như tự động hóa, trí tuệ nhân tạo (AI), internet vạn vật (IoT) nhằm nâng cao năng suất và hiệu quả sản xuất.',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-service-6',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-service',
  subject: 'history_geography',
  prompt: 'Việt Nam chính thức trở thành thành viên của Tổ chức Thương mại Thế giới (WTO) vào ngày tháng năm nào?',
  options: ['11/1/2007', '1/1/2000', '28/7/1995', '1/1/2010'],
  correctAnswer: '11/1/2007',
  explanation: 'Ngày 11/1/2007, Việt Nam chính thức trở thành thành viên thứ 150 của Tổ chức Thương mại Thế giới (WTO), mở ra giai đoạn hội nhập kinh tế quốc tế sâu rộng.',
  difficulty: 1,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-service-7',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-service',
  subject: 'history_geography',
  prompt: 'Việt Nam là thành viên thứ bao nhiêu của Tổ chức Thương mại Thế giới (WTO)?',
  options: ['Thành viên thứ 150', 'Thành viên thứ 100', 'Thành viên thứ 200', 'Thành viên thứ 50'],
  correctAnswer: 'Thành viên thứ 150',
  explanation: 'Việt Nam gia nhập WTO với tư cách là thành viên thứ 150 của tổ chức này vào ngày 11/1/2007.',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-service-8',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-service',
  subject: 'history_geography',
  prompt: 'Vịnh Hạ Long, một trong những điểm du lịch nổi tiếng nhất Việt Nam, được UNESCO công nhận là Di sản Thiên nhiên Thế giới lần đầu vào năm nào?',
  options: ['1994', '1999', '2003', '1986'],
  correctAnswer: '1994',
  explanation: 'Vịnh Hạ Long được UNESCO công nhận là Di sản Thiên nhiên Thế giới lần đầu tiên vào năm 1994 và được công nhận lần thứ hai năm 2000.',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-service-9',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-service',
  subject: 'history_geography',
  prompt: 'Vườn quốc gia Phong Nha - Kẻ Bàng, một di sản thiên nhiên thế giới nổi tiếng với hệ thống hang động, thuộc tỉnh nào?',
  options: ['Quảng Bình', 'Quảng Nam', 'Ninh Bình', 'Hà Giang'],
  correctAnswer: 'Quảng Bình',
  explanation: 'Vườn quốc gia Phong Nha - Kẻ Bàng thuộc tỉnh Quảng Bình, được UNESCO công nhận là Di sản Thiên nhiên Thế giới nhờ hệ thống hang động kỳ vĩ.',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-service-10',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-service',
  subject: 'history_geography',
  prompt: 'Nông sản nào sau đây là một trong những mặt hàng xuất khẩu chủ lực của Việt Nam, đứng đầu thế giới về sản lượng xuất khẩu?',
  options: ['Hạt điều và hạt tiêu', 'Ngô', 'Khoai lang', 'Đậu tương'],
  correctAnswer: 'Hạt điều và hạt tiêu',
  explanation: 'Việt Nam là quốc gia xuất khẩu hạt điều và hạt tiêu đứng đầu thế giới, bên cạnh các mặt hàng nông sản chủ lực khác như gạo, cà phê, cao su.',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-service-11',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-service',
  subject: 'history_geography',
  prompt: 'Hoạt động nội thương (thương mại trong nước) của Việt Nam bao gồm những hình thức phân phối chủ yếu nào?',
  options: ['Chợ, siêu thị, trung tâm thương mại, cửa hàng tiện lợi', 'Chỉ có chợ truyền thống', 'Chỉ có siêu thị', 'Chỉ có thương mại điện tử'],
  correctAnswer: 'Chợ, siêu thị, trung tâm thương mại, cửa hàng tiện lợi',
  explanation: 'Nội thương Việt Nam phát triển đa dạng với các hình thức: chợ truyền thống, siêu thị, trung tâm thương mại và cửa hàng tiện lợi, đáp ứng nhu cầu tiêu dùng ngày càng cao.',
  difficulty: 1,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-service-12',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-service',
  subject: 'history_geography',
  prompt: 'Xu hướng nào đang phát triển mạnh mẽ trong hoạt động thương mại nội địa của Việt Nam hiện nay?',
  options: ['Thương mại điện tử', 'Chỉ giao dịch tiền mặt truyền thống', 'Giảm quy mô bán lẻ', 'Ngừng phát triển siêu thị'],
  correctAnswer: 'Thương mại điện tử',
  explanation: 'Thương mại điện tử đang phát triển mạnh mẽ nhờ sự phổ biến của internet và điện thoại thông minh, trở thành xu hướng nổi bật trong nội thương Việt Nam.',
  difficulty: 1,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-service-13',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-service',
  subject: 'history_geography',
  prompt: 'Đảo Phú Quốc, một trong những trung tâm du lịch biển đảo lớn của Việt Nam, thuộc tỉnh nào?',
  options: ['Kiên Giang', 'Cà Mau', 'Bà Rịa - Vũng Tàu', 'Khánh Hòa'],
  correctAnswer: 'Kiên Giang',
  explanation: 'Đảo Phú Quốc thuộc tỉnh Kiên Giang, là hòn đảo lớn nhất Việt Nam và là trung tâm du lịch biển đảo nổi tiếng, thu hút đông đảo du khách trong và ngoài nước.',
  difficulty: 1,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-service-14',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-service',
  subject: 'history_geography',
  prompt: 'Quần thể di tích Cố đô Huế được UNESCO công nhận là Di sản Văn hóa Thế giới vào năm nào?',
  options: ['1993', '1994', '2000', '2003'],
  correctAnswer: '1993',
  explanation: 'Quần thể di tích Cố đô Huế được UNESCO công nhận là Di sản Văn hóa Thế giới vào năm 1993, là di sản văn hóa thế giới đầu tiên của Việt Nam.',
  difficulty: 3,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-service-15',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-service',
  subject: 'history_geography',
  prompt: 'Việc gia nhập WTO đã mang lại cơ hội gì cho ngành dịch vụ và ngoại thương của Việt Nam?',
  options: [
    'Mở rộng thị trường xuất khẩu, thu hút đầu tư nước ngoài, tiếp cận công nghệ mới',
    'Đóng cửa hoàn toàn với thị trường quốc tế',
    'Giảm kim ngạch xuất nhập khẩu',
    'Loại bỏ ngành dịch vụ trong nước'
  ],
  correctAnswer: 'Mở rộng thị trường xuất khẩu, thu hút đầu tư nước ngoài, tiếp cận công nghệ mới',
  explanation: 'Gia nhập WTO giúp Việt Nam mở rộng thị trường xuất khẩu, thu hút mạnh mẽ vốn đầu tư nước ngoài (FDI) và tiếp cận công nghệ, quản lý tiên tiến, thúc đẩy ngành dịch vụ phát triển.',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-regions-6',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-regions-7',
  subject: 'history_geography',
  prompt: 'Việt Nam được phân chia thành mấy vùng kinh tế theo cách phân vùng truyền thống trong chương trình Địa lý lớp 9?',
  options: ['7 vùng', '6 vùng', '5 vùng', '8 vùng'],
  correctAnswer: '7 vùng',
  explanation: 'Theo cách phân vùng truyền thống, Việt Nam được chia thành 7 vùng kinh tế: Trung du miền núi Bắc Bộ, Đồng bằng sông Hồng, Bắc Trung Bộ, Duyên hải Nam Trung Bộ, Tây Nguyên, Đông Nam Bộ và Đồng bằng sông Cửu Long.',
  difficulty: 1,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-regions-7',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-regions-7',
  subject: 'history_geography',
  prompt: 'Vùng nào có diện tích lớn nhất trong 7 vùng kinh tế của Việt Nam?',
  options: ['Trung du và miền núi Bắc Bộ', 'Đồng bằng sông Hồng', 'Đông Nam Bộ', 'Tây Nguyên'],
  correctAnswer: 'Trung du và miền núi Bắc Bộ',
  explanation: 'Trung du và miền núi Bắc Bộ là vùng có diện tích lớn nhất cả nước, tiếp giáp Trung Quốc và Lào, có nhiều tiềm năng về khoáng sản và thủy điện.',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-regions-8',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-regions-7',
  subject: 'history_geography',
  prompt: 'Vùng nào là vùng có mật độ dân số cao nhất, là vựa lúa lớn thứ hai cả nước?',
  options: ['Đồng bằng sông Hồng', 'Tây Nguyên', 'Trung du miền núi Bắc Bộ', 'Bắc Trung Bộ'],
  correctAnswer: 'Đồng bằng sông Hồng',
  explanation: 'Đồng bằng sông Hồng là vùng đông dân nhất cả nước, đồng thời là vựa lúa lớn thứ hai sau Đồng bằng sông Cửu Long.',
  difficulty: 1,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-regions-9',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-regions-7',
  subject: 'history_geography',
  prompt: 'Vùng nào có đặc điểm là dải đất hẹp, thường xuyên chịu ảnh hưởng của bão, lũ lụt, gió phơn Tây Nam khô nóng?',
  options: ['Bắc Trung Bộ', 'Tây Nguyên', 'Đông Nam Bộ', 'Đồng bằng sông Cửu Long'],
  correctAnswer: 'Bắc Trung Bộ',
  explanation: 'Bắc Trung Bộ là dải đất hẹp ngang, chịu ảnh hưởng nặng nề của bão, lũ lụt vào mùa mưa và gió phơn Tây Nam khô nóng vào mùa hè.',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-regions-10',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-regions-7',
  subject: 'history_geography',
  prompt: 'Vùng nào có thế mạnh nổi bật về kinh tế biển, đặc biệt là đánh bắt và nuôi trồng thủy sản, cùng du lịch biển?',
  options: ['Duyên hải Nam Trung Bộ', 'Trung du miền núi Bắc Bộ', 'Tây Nguyên', 'Đồng bằng sông Hồng'],
  correctAnswer: 'Duyên hải Nam Trung Bộ',
  explanation: 'Duyên hải Nam Trung Bộ có đường bờ biển dài, nhiều ngư trường lớn và bãi biển đẹp, là thế mạnh về kinh tế biển và du lịch biển.',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-regions-11',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-regions-7',
  subject: 'history_geography',
  prompt: 'Vùng nào có địa hình cao nguyên xếp tầng, đất badan màu mỡ, là vùng chuyên canh cây công nghiệp lâu năm lớn nhất cả nước?',
  options: ['Tây Nguyên', 'Đông Nam Bộ', 'Bắc Trung Bộ', 'Trung du miền núi Bắc Bộ'],
  correctAnswer: 'Tây Nguyên',
  explanation: 'Tây Nguyên có địa hình cao nguyên xếp tầng với đất badan màu mỡ, là vùng chuyên canh cây công nghiệp lâu năm (cà phê, cao su, hồ tiêu) lớn nhất cả nước.',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-regions-12',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-regions-7',
  subject: 'history_geography',
  prompt: 'Vùng nào có tốc độ phát triển kinh tế cao nhất, GDP bình quân đầu người cao nhất cả nước?',
  options: ['Đông Nam Bộ', 'Bắc Trung Bộ', 'Tây Nguyên', 'Trung du miền núi Bắc Bộ'],
  correctAnswer: 'Đông Nam Bộ',
  explanation: 'Đông Nam Bộ là vùng kinh tế phát triển năng động nhất, có GDP bình quân đầu người và tốc độ tăng trưởng kinh tế cao nhất cả nước.',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-regions-13',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-regions-7',
  subject: 'history_geography',
  prompt: 'Vùng nào là vùng sản xuất lương thực, thực phẩm (lúa gạo, thủy sản) lớn nhất cả nước?',
  options: ['Đồng bằng sông Cửu Long', 'Đông Nam Bộ', 'Tây Nguyên', 'Trung du miền núi Bắc Bộ'],
  correctAnswer: 'Đồng bằng sông Cửu Long',
  explanation: 'Đồng bằng sông Cửu Long là vùng trọng điểm sản xuất lương thực, thực phẩm lớn nhất cả nước, đặc biệt về lúa gạo và thủy sản.',
  difficulty: 1,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-regions-14',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-regions-7',
  subject: 'history_geography',
  prompt: 'Đồng bằng sông Cửu Long đang đối mặt với thách thức môi trường nghiêm trọng nào do biến đổi khí hậu?',
  options: ['Xâm nhập mặn', 'Bão tuyết', 'Động đất', 'Sương muối'],
  correctAnswer: 'Xâm nhập mặn',
  explanation: 'Đồng bằng sông Cửu Long đang chịu ảnh hưởng nghiêm trọng của xâm nhập mặn do biến đổi khí hậu và nước biển dâng, ảnh hưởng đến sản xuất nông nghiệp.',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-regions-15',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-regions-7',
  subject: 'history_geography',
  prompt: 'Vùng Trung du và miền núi Bắc Bộ có thế mạnh nổi bật nào về công nghiệp năng lượng?',
  options: ['Khai thác than và thủy điện', 'Khai thác dầu khí', 'Điện gió ngoài khơi', 'Điện mặt trời áp mái'],
  correctAnswer: 'Khai thác than và thủy điện',
  explanation: 'Trung du và miền núi Bắc Bộ có thế mạnh về khai thác than (Quảng Ninh) và thủy điện (Hòa Bình, Sơn La) nhờ địa hình đồi núi và trữ lượng khoáng sản phong phú.',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-regions-16',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-regions-7',
  subject: 'history_geography',
  prompt: 'Trung tâm kinh tế, chính trị, văn hóa lớn nhất của vùng Đồng bằng sông Hồng là thành phố nào?',
  options: ['Hà Nội', 'Hải Phòng', 'Nam Định', 'Ninh Bình'],
  correctAnswer: 'Hà Nội',
  explanation: 'Hà Nội là thủ đô, đồng thời là trung tâm kinh tế, chính trị, văn hóa lớn nhất của vùng Đồng bằng sông Hồng và cả nước.',
  difficulty: 1,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-regions-17',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-regions-7',
  subject: 'history_geography',
  prompt: 'Nhà máy lọc dầu Dung Quất, cơ sở lọc hóa dầu đầu tiên của Việt Nam, thuộc vùng kinh tế nào?',
  options: ['Duyên hải Nam Trung Bộ', 'Đông Nam Bộ', 'Bắc Trung Bộ', 'Đồng bằng sông Hồng'],
  correctAnswer: 'Duyên hải Nam Trung Bộ',
  explanation: 'Nhà máy lọc dầu Dung Quất đặt tại tỉnh Quảng Ngãi, thuộc vùng Duyên hải Nam Trung Bộ, là nhà máy lọc hóa dầu đầu tiên của Việt Nam.',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-regions-18',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-regions-7',
  subject: 'history_geography',
  prompt: 'Vùng nào có số lượng đồng bào dân tộc ít người sinh sống đông đảo nhất, gắn với thế mạnh phát triển cây công nghiệp lâu năm và thủy điện?',
  options: ['Tây Nguyên', 'Đồng bằng sông Hồng', 'Đông Nam Bộ', 'Đồng bằng sông Cửu Long'],
  correctAnswer: 'Tây Nguyên',
  explanation: 'Tây Nguyên là địa bàn cư trú của nhiều dân tộc ít người (Ê-đê, Gia-rai, Ba-na...), đồng thời có thế mạnh về cây công nghiệp lâu năm và thủy điện.',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-regions-19',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-regions-7',
  subject: 'history_geography',
  prompt: 'Vùng kinh tế nào của Việt Nam giáp biển Đông ở phía Đông và giáp Campuchia ở phía Tây, có hệ thống kênh rạch chằng chịt?',
  options: ['Đồng bằng sông Cửu Long', 'Đông Nam Bộ', 'Bắc Trung Bộ', 'Duyên hải Nam Trung Bộ'],
  correctAnswer: 'Đồng bằng sông Cửu Long',
  explanation: 'Đồng bằng sông Cửu Long giáp biển Đông, giáp Campuchia, có hệ thống sông ngòi, kênh rạch chằng chịt, thuận lợi cho nông nghiệp và giao thông đường thủy.',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
},
{
  id: 'gk-geo-regions-20',
  type: 'mcq',
  category: 'geography',
  topicId: 'geo-regions-7',
  subject: 'history_geography',
  prompt: 'Vùng Đông Nam Bộ có cảng biển và cụm cảng lớn nào đóng vai trò quan trọng trong xuất nhập khẩu hàng hóa?',
  options: ['Cảng Sài Gòn và cụm cảng Cái Mép - Thị Vải', 'Cảng Hải Phòng', 'Cảng Đà Nẵng', 'Cảng Quy Nhơn'],
  correctAnswer: 'Cảng Sài Gòn và cụm cảng Cái Mép - Thị Vải',
  explanation: 'Cảng Sài Gòn và cụm cảng nước sâu Cái Mép - Thị Vải (Bà Rịa - Vũng Tàu) là cửa ngõ xuất nhập khẩu hàng hóa quan trọng bậc nhất của vùng Đông Nam Bộ và cả nước.',
  difficulty: 2,
  source: 'GDPT 2018 - Địa lý lớp 9'
}
