{
  id: 'gk-tech-jobs-6',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-career-jobs',
  subject: 'technology',
  prompt: 'Kỹ sư điện thường làm việc trong lĩnh vực nào?',
  options: ['Thiết kế, lắp đặt và vận hành hệ thống điện', 'Chế biến thực phẩm', 'Thiết kế thời trang', 'Chăm sóc sức khỏe'],
  correctAnswer: 'Thiết kế, lắp đặt và vận hành hệ thống điện',
  explanation: 'Kỹ sư điện chuyên thiết kế, lắp đặt, vận hành và bảo trì các hệ thống điện, thiết bị điện.',
  difficulty: 1,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-jobs-7',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-career-jobs',
  subject: 'technology',
  prompt: 'Kỹ thuật viên bảo trì máy tính chủ yếu thực hiện công việc gì?',
  options: ['Sửa chữa, bảo dưỡng phần cứng và phần mềm máy tính', 'Viết nhạc', 'Thiết kế nội thất', 'Nấu ăn'],
  correctAnswer: 'Sửa chữa, bảo dưỡng phần cứng và phần mềm máy tính',
  explanation: 'Kỹ thuật viên bảo trì máy tính có nhiệm vụ kiểm tra, sửa chữa, bảo dưỡng phần cứng và phần mềm.',
  difficulty: 1,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-jobs-8',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-career-jobs',
  subject: 'technology',
  prompt: 'Đặc điểm nào sau đây thường gắn với nghề kĩ thuật, công nghệ?',
  options: ['Đòi hỏi tư duy logic và khả năng giải quyết vấn đề kỹ thuật', 'Không cần đào tạo chuyên môn', 'Chỉ làm việc ngoài trời', 'Không liên quan đến máy móc, thiết bị'],
  correctAnswer: 'Đòi hỏi tư duy logic và khả năng giải quyết vấn đề kỹ thuật',
  explanation: 'Nghề kĩ thuật, công nghệ thường yêu cầu tư duy logic, khả năng phân tích và giải quyết các vấn đề kỹ thuật.',
  difficulty: 2,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-jobs-9',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-career-jobs',
  subject: 'technology',
  prompt: 'Kỹ sư xây dựng có nhiệm vụ chính là gì?',
  options: ['Thiết kế, thi công và giám sát các công trình xây dựng', 'Soạn thảo văn bản pháp luật', 'Biểu diễn nghệ thuật', 'Kinh doanh bất động sản'],
  correctAnswer: 'Thiết kế, thi công và giám sát các công trình xây dựng',
  explanation: 'Kỹ sư xây dựng đảm nhiệm việc thiết kế, tổ chức thi công và giám sát chất lượng công trình.',
  difficulty: 1,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-jobs-10',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-career-jobs',
  subject: 'technology',
  prompt: 'Người làm nghề lập trình viên cần có kỹ năng nổi bật nào?',
  options: ['Tư duy thuật toán và kỹ năng viết mã (code)', 'Kỹ năng vẽ tranh', 'Kỹ năng nấu ăn', 'Kỹ năng may vá'],
  correctAnswer: 'Tư duy thuật toán và kỹ năng viết mã (code)',
  explanation: 'Lập trình viên cần tư duy thuật toán tốt và thành thạo kỹ năng viết, kiểm thử mã nguồn.',
  difficulty: 1,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-jobs-11',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-career-jobs',
  subject: 'technology',
  prompt: 'Kỹ sư cơ điện tử (mechatronics) làm việc chủ yếu với lĩnh vực nào?',
  options: ['Kết hợp cơ khí, điện tử và điều khiển tự động', 'Chỉ riêng ngành may mặc', 'Chỉ riêng ngành ẩm thực', 'Chỉ riêng ngành du lịch'],
  correctAnswer: 'Kết hợp cơ khí, điện tử và điều khiển tự động',
  explanation: 'Kỹ sư cơ điện tử làm việc trong lĩnh vực tích hợp giữa cơ khí, điện tử và hệ thống điều khiển tự động.',
  difficulty: 2,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-jobs-12',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-career-jobs',
  subject: 'technology',
  prompt: 'Thợ điện dân dụng thường thực hiện công việc nào?',
  options: ['Lắp đặt và sửa chữa hệ thống điện trong nhà ở', 'Thiết kế phần mềm', 'Dịch thuật văn bản', 'Chăm sóc cây cảnh'],
  correctAnswer: 'Lắp đặt và sửa chữa hệ thống điện trong nhà ở',
  explanation: 'Thợ điện dân dụng chuyên lắp đặt, sửa chữa hệ thống điện, thiết bị điện trong hộ gia đình.',
  difficulty: 1,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-jobs-13',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-career-jobs',
  subject: 'technology',
  prompt: 'Yếu tố an toàn lao động quan trọng nhất đối với nghề kĩ thuật, công nghệ là gì?',
  options: ['Tuân thủ quy trình và trang bị bảo hộ lao động', 'Làm việc càng nhanh càng tốt bất kể quy trình', 'Không cần quan tâm đến an toàn', 'Chỉ cần kinh nghiệm cá nhân'],
  correctAnswer: 'Tuân thủ quy trình và trang bị bảo hộ lao động',
  explanation: 'An toàn lao động trong nghề kĩ thuật đòi hỏi tuân thủ đúng quy trình kỹ thuật và sử dụng đầy đủ trang bị bảo hộ.',
  difficulty: 1,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-jobs-14',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-career-jobs',
  subject: 'technology',
  prompt: 'Kỹ sư ô tô thường đảm nhiệm công việc nào?',
  options: ['Thiết kế, chế tạo và sửa chữa các bộ phận ô tô', 'Thiết kế trang phục', 'Sáng tác thơ ca', 'Quản lý nhà hàng'],
  correctAnswer: 'Thiết kế, chế tạo và sửa chữa các bộ phận ô tô',
  explanation: 'Kỹ sư ô tô chuyên nghiên cứu, thiết kế, chế tạo và sửa chữa các hệ thống, bộ phận của ô tô.',
  difficulty: 1,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-jobs-15',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-career-jobs',
  subject: 'technology',
  prompt: 'Nghề nào sau đây KHÔNG thuộc lĩnh vực kĩ thuật, công nghệ?',
  options: ['Ca sĩ biểu diễn', 'Kỹ sư điện tử', 'Kỹ thuật viên cơ khí', 'Kỹ sư xây dựng'],
  correctAnswer: 'Ca sĩ biểu diễn',
  explanation: 'Ca sĩ biểu diễn thuộc lĩnh vực nghệ thuật, không phải nghề kĩ thuật, công nghệ.',
  difficulty: 1,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-edu-6',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-career-education',
  subject: 'technology',
  prompt: 'Trong hệ thống giáo dục nghề nghiệp Việt Nam, trình độ nào thấp nhất?',
  options: ['Sơ cấp', 'Trung cấp', 'Cao đẳng', 'Đại học'],
  correctAnswer: 'Sơ cấp',
  explanation: 'Hệ thống giáo dục nghề nghiệp Việt Nam gồm ba cấp trình độ: sơ cấp, trung cấp, cao đẳng, trong đó sơ cấp là trình độ đào tạo cơ bản nhất.',
  difficulty: 1,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-edu-7',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-career-education',
  subject: 'technology',
  prompt: 'Thời gian đào tạo trình độ trung cấp thường kéo dài bao lâu?',
  options: ['Từ 1 đến 2 năm', '6 tháng', '5 năm', '10 năm'],
  correctAnswer: 'Từ 1 đến 2 năm',
  explanation: 'Đào tạo trình độ trung cấp thường có thời gian từ 1 đến 2 năm tùy theo ngành nghề và đối tượng tuyển sinh.',
  difficulty: 2,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-edu-8',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-career-education',
  subject: 'technology',
  prompt: 'Học sinh tốt nghiệp THCS có thể theo học hệ nào để vừa học văn hóa vừa học nghề?',
  options: ['Trung cấp nghề (hệ 9+)', 'Đại học chính quy', 'Sau đại học', 'Nghiên cứu sinh'],
  correctAnswer: 'Trung cấp nghề (hệ 9+)',
  explanation: 'Học sinh tốt nghiệp THCS có thể theo học hệ trung cấp nghề (thường gọi là hệ 9+) để học song song văn hóa và nghề.',
  difficulty: 2,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-edu-9',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-career-education',
  subject: 'technology',
  prompt: 'Trình độ đào tạo nào cung cấp bằng cử nhân hoặc kỹ sư?',
  options: ['Đại học', 'Sơ cấp', 'Trung cấp', 'Cao đẳng'],
  correctAnswer: 'Đại học',
  explanation: 'Trình độ đại học đào tạo và cấp bằng cử nhân hoặc kỹ sư sau khi hoàn thành chương trình học.',
  difficulty: 1,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-edu-10',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-career-education',
  subject: 'technology',
  prompt: 'Trình độ cao đẳng thường có thời gian đào tạo bao lâu đối với người tốt nghiệp THPT?',
  options: ['Khoảng 2 đến 3 năm', '6 tháng', '6 năm', '10 năm'],
  correctAnswer: 'Khoảng 2 đến 3 năm',
  explanation: 'Đào tạo trình độ cao đẳng đối với người đã tốt nghiệp THPT thường kéo dài từ 2 đến 3 năm.',
  difficulty: 2,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-edu-11',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-career-education',
  subject: 'technology',
  prompt: 'Cơ sở giáo dục nào chuyên đào tạo trình độ sơ cấp, trung cấp, cao đẳng nghề?',
  options: ['Trường cao đẳng, trung tâm giáo dục nghề nghiệp', 'Trường mầm non', 'Viện nghiên cứu khoa học cơ bản', 'Trường tiểu học'],
  correctAnswer: 'Trường cao đẳng, trung tâm giáo dục nghề nghiệp',
  explanation: 'Trường cao đẳng và trung tâm giáo dục nghề nghiệp là nơi đào tạo các trình độ sơ cấp, trung cấp, cao đẳng.',
  difficulty: 2,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-edu-12',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-career-education',
  subject: 'technology',
  prompt: 'Sau khi tốt nghiệp THCS, học sinh có định hướng học nghề kĩ thuật có thể lựa chọn con đường nào?',
  options: ['Học trung cấp nghề kết hợp học văn hóa', 'Học sau đại học ngay lập tức', 'Không cần học tiếp', 'Chỉ được học đại học'],
  correctAnswer: 'Học trung cấp nghề kết hợp học văn hóa',
  explanation: 'Sau THCS, học sinh có thể chọn học trung cấp nghề kết hợp học văn hóa để sớm tiếp cận nghề kĩ thuật.',
  difficulty: 1,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-edu-13',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-career-education',
  subject: 'technology',
  prompt: 'Trình độ sơ cấp trong giáo dục nghề nghiệp phù hợp với mục tiêu nào?',
  options: ['Đào tạo kỹ năng nghề cơ bản trong thời gian ngắn', 'Đào tạo tiến sĩ', 'Đào tạo thạc sĩ', 'Nghiên cứu chuyên sâu dài hạn'],
  correctAnswer: 'Đào tạo kỹ năng nghề cơ bản trong thời gian ngắn',
  explanation: 'Trình độ sơ cấp nhằm trang bị kỹ năng nghề cơ bản, thời gian đào tạo ngắn, giúp người học nhanh chóng tham gia lao động.',
  difficulty: 1,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-edu-14',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-career-education',
  subject: 'technology',
  prompt: 'Bằng cấp nào được cấp sau khi hoàn thành chương trình cao đẳng?',
  options: ['Bằng cao đẳng', 'Bằng tiến sĩ', 'Chứng chỉ sơ cấp', 'Bằng thạc sĩ'],
  correctAnswer: 'Bằng cao đẳng',
  explanation: 'Người học hoàn thành chương trình đào tạo trình độ cao đẳng sẽ được cấp bằng cao đẳng.',
  difficulty: 1,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-edu-15',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-career-education',
  subject: 'technology',
  prompt: 'Hệ thống giáo dục nghề nghiệp Việt Nam được sắp xếp theo thứ tự trình độ tăng dần nào?',
  options: ['Sơ cấp - Trung cấp - Cao đẳng', 'Cao đẳng - Sơ cấp - Trung cấp', 'Trung cấp - Cao đẳng - Sơ cấp', 'Cao đẳng - Trung cấp - Sơ cấp'],
  correctAnswer: 'Sơ cấp - Trung cấp - Cao đẳng',
  explanation: 'Thứ tự trình độ tăng dần trong giáo dục nghề nghiệp là sơ cấp, trung cấp, rồi đến cao đẳng.',
  difficulty: 2,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-market-6',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-career-market',
  subject: 'technology',
  prompt: 'Cách mạng công nghiệp 4.0 có đặc trưng nổi bật nào?',
  options: ['Ứng dụng trí tuệ nhân tạo, tự động hóa và kết nối internet vạn vật', 'Chỉ sử dụng sức lao động thủ công', 'Không sử dụng máy móc', 'Chỉ tập trung vào nông nghiệp truyền thống'],
  correctAnswer: 'Ứng dụng trí tuệ nhân tạo, tự động hóa và kết nối internet vạn vật',
  explanation: 'Cách mạng công nghiệp 4.0 đặc trưng bởi sự ứng dụng mạnh mẽ trí tuệ nhân tạo (AI), tự động hóa và IoT.',
  difficulty: 1,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-market-7',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-career-market',
  subject: 'technology',
  prompt: 'Nhu cầu nhân lực ngành nào đang tăng cao trong thị trường lao động Việt Nam hiện nay?',
  options: ['Công nghệ thông tin và tự động hóa', 'Đánh bắt thủy sản thủ công', 'Dệt vải bằng khung cửi truyền thống', 'Sản xuất nông cụ thô sơ'],
  correctAnswer: 'Công nghệ thông tin và tự động hóa',
  explanation: 'Trong bối cảnh chuyển đổi số, nhu cầu nhân lực ngành công nghệ thông tin và tự động hóa đang tăng mạnh.',
  difficulty: 2,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-market-8',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-career-market',
  subject: 'technology',
  prompt: 'Kỹ năng nào được xem là cần thiết để thích ứng với thị trường lao động thời đại số?',
  options: ['Kỹ năng sử dụng công nghệ thông tin và học tập suốt đời', 'Chỉ cần sức khỏe tốt', 'Chỉ cần ngoại hình', 'Không cần kỹ năng gì đặc biệt'],
  correctAnswer: 'Kỹ năng sử dụng công nghệ thông tin và học tập suốt đời',
  explanation: 'Thời đại số đòi hỏi người lao động có kỹ năng công nghệ thông tin và tinh thần học tập suốt đời để thích ứng.',
  difficulty: 2,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-market-9',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-career-market',
  subject: 'technology',
  prompt: 'Yếu tố nào ảnh hưởng lớn đến sự thay đổi của thị trường lao động kĩ thuật, công nghệ?',
  options: ['Sự phát triển của khoa học công nghệ', 'Thời tiết theo mùa', 'Sở thích cá nhân của người lao động', 'Số lượng ngày lễ trong năm'],
  correctAnswer: 'Sự phát triển của khoa học công nghệ',
  explanation: 'Sự phát triển nhanh chóng của khoa học công nghệ làm thay đổi cơ cấu và nhu cầu của thị trường lao động.',
  difficulty: 2,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-market-10',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-career-market',
  subject: 'technology',
  prompt: 'Robot và tự động hóa trong sản xuất có xu hướng tác động thế nào đến thị trường lao động?',
  options: ['Thay thế một số công việc thủ công, đồng thời tạo ra nghề mới đòi hỏi kỹ năng cao', 'Không tác động gì', 'Chỉ làm giảm số lượng nghề nghiệp mà không tạo ra nghề mới', 'Chỉ áp dụng trong nông nghiệp'],
  correctAnswer: 'Thay thế một số công việc thủ công, đồng thời tạo ra nghề mới đòi hỏi kỹ năng cao',
  explanation: 'Tự động hóa vừa thay thế lao động thủ công giản đơn, vừa mở ra các nghề mới đòi hỏi trình độ kỹ thuật cao hơn.',
  difficulty: 3,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-market-11',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-career-market',
  subject: 'technology',
  prompt: 'Internet vạn vật (IoT) là gì?',
  options: ['Mạng lưới kết nối các thiết bị thông qua internet để thu thập, trao đổi dữ liệu', 'Một loại virus máy tính', 'Một phần mềm soạn thảo văn bản', 'Một thiết bị điện gia dụng'],
  correctAnswer: 'Mạng lưới kết nối các thiết bị thông qua internet để thu thập, trao đổi dữ liệu',
  explanation: 'IoT (Internet of Things) là mạng lưới các thiết bị được kết nối qua internet nhằm thu thập và trao đổi dữ liệu.',
  difficulty: 2,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-market-12',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-career-market',
  subject: 'technology',
  prompt: 'Vì sao người lao động cần thường xuyên cập nhật kiến thức, kỹ năng công nghệ mới?',
  options: ['Vì công nghệ thay đổi nhanh, nếu không cập nhật sẽ khó đáp ứng yêu cầu công việc', 'Vì công nghệ không bao giờ thay đổi', 'Vì công việc không liên quan đến công nghệ', 'Vì không ảnh hưởng đến cơ hội việc làm'],
  correctAnswer: 'Vì công nghệ thay đổi nhanh, nếu không cập nhật sẽ khó đáp ứng yêu cầu công việc',
  explanation: 'Công nghệ phát triển nhanh chóng nên người lao động cần liên tục học hỏi, cập nhật để đáp ứng yêu cầu công việc.',
  difficulty: 2,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-market-13',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-career-market',
  subject: 'technology',
  prompt: 'Trí tuệ nhân tạo (AI) đang được ứng dụng phổ biến trong lĩnh vực nào?',
  options: ['Sản xuất thông minh, y tế, giao thông và dịch vụ', 'Chỉ trong nấu ăn gia đình', 'Chỉ trong nông nghiệp thủ công', 'Không được ứng dụng trong thực tế'],
  correctAnswer: 'Sản xuất thông minh, y tế, giao thông và dịch vụ',
  explanation: 'AI được ứng dụng rộng rãi trong sản xuất thông minh, y tế, giao thông, dịch vụ và nhiều lĩnh vực khác.',
  difficulty: 2,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-market-14',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-career-market',
  subject: 'technology',
  prompt: 'Thị trường lao động kĩ thuật, công nghệ Việt Nam hiện nay có xu hướng nào?',
  options: ['Nhu cầu lao động có kỹ năng chuyên môn cao ngày càng tăng', 'Nhu cầu lao động phổ thông không kỹ năng tăng mạnh', 'Không có sự thay đổi nào', 'Giảm nhu cầu tuyển dụng ở mọi lĩnh vực'],
  correctAnswer: 'Nhu cầu lao động có kỹ năng chuyên môn cao ngày càng tăng',
  explanation: 'Thị trường lao động đang chuyển dịch theo hướng cần nhiều lao động có kỹ năng chuyên môn, tay nghề cao.',
  difficulty: 2,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-market-15',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-career-market',
  subject: 'technology',
  prompt: 'Chuyển đổi số là gì?',
  options: ['Quá trình ứng dụng công nghệ số vào hoạt động sản xuất, quản lý và đời sống', 'Việc chuyển đổi tiền tệ giữa các quốc gia', 'Việc số hóa chỉ áp dụng cho sách giáo khoa', 'Một môn thể thao mới'],
  correctAnswer: 'Quá trình ứng dụng công nghệ số vào hoạt động sản xuất, quản lý và đời sống',
  explanation: 'Chuyển đổi số là quá trình ứng dụng công nghệ số để thay đổi cách thức sản xuất, quản lý, vận hành và sinh hoạt.',
  difficulty: 2,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-choice-6',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-career-choice',
  subject: 'technology',
  prompt: 'Bước đầu tiên trong quy trình lựa chọn nghề nghiệp là gì?',
  options: ['Tự nhận thức bản thân (sở thích, năng lực, tính cách)', 'Nộp hồ sơ xin việc ngay', 'Ký hợp đồng lao động', 'Nghỉ việc'],
  correctAnswer: 'Tự nhận thức bản thân (sở thích, năng lực, tính cách)',
  explanation: 'Quy trình chọn nghề bắt đầu bằng việc tự nhận thức bản thân về sở thích, năng lực và tính cách của mình.',
  difficulty: 1,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-choice-7',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-career-choice',
  subject: 'technology',
  prompt: 'Khi lựa chọn nghề nghiệp, cần cân nhắc yếu tố nào sau đây?',
  options: ['Sở thích, năng lực bản thân và nhu cầu thị trường lao động', 'Chỉ dựa vào ý kiến của bạn bè', 'Chỉ chọn nghề có thu nhập cao nhất mà không cần phù hợp năng lực', 'Chọn ngẫu nhiên không cần suy nghĩ'],
  correctAnswer: 'Sở thích, năng lực bản thân và nhu cầu thị trường lao động',
  explanation: 'Lựa chọn nghề nghiệp cần dựa trên sự phù hợp giữa sở thích, năng lực cá nhân và nhu cầu thực tế của thị trường lao động.',
  difficulty: 1,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-choice-8',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-career-choice',
  subject: 'technology',
  prompt: 'Kế hoạch nghề nghiệp cá nhân nên bao gồm nội dung nào?',
  options: ['Mục tiêu nghề nghiệp và các bước học tập, rèn luyện để đạt mục tiêu', 'Chỉ ghi tên nghề mong muốn mà không có kế hoạch cụ thể', 'Danh sách các trò chơi giải trí', 'Lịch trình đi du lịch'],
  correctAnswer: 'Mục tiêu nghề nghiệp và các bước học tập, rèn luyện để đạt mục tiêu',
  explanation: 'Kế hoạch nghề nghiệp cần xác định rõ mục tiêu và các bước cụ thể để học tập, rèn luyện nhằm đạt được mục tiêu đó.',
  difficulty: 2,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-choice-9',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-career-choice',
  subject: 'technology',
  prompt: 'Giá trị nghề nghiệp là gì?',
  options: ['Những điều quan trọng mà cá nhân mong muốn đạt được qua công việc', 'Số tiền lương cố định hằng tháng', 'Tên gọi chính thức của nghề', 'Trang phục khi làm việc'],
  correctAnswer: 'Những điều quan trọng mà cá nhân mong muốn đạt được qua công việc',
  explanation: 'Giá trị nghề nghiệp là những điều cá nhân coi trọng và mong muốn đạt được thông qua công việc, như sự ổn định, sáng tạo, cống hiến.',
  difficulty: 2,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-choice-10',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-career-choice',
  subject: 'technology',
  prompt: 'Vì sao cần tìm hiểu thông tin thị trường lao động trước khi chọn nghề?',
  options: ['Để biết nhu cầu tuyển dụng và cơ hội việc làm của nghề đó', 'Vì không có lý do gì cần thiết', 'Để chọn nghề theo trào lưu mà không cân nhắc', 'Chỉ để tham khảo cho vui'],
  correctAnswer: 'Để biết nhu cầu tuyển dụng và cơ hội việc làm của nghề đó',
  explanation: 'Tìm hiểu thị trường lao động giúp người chọn nghề nắm được nhu cầu tuyển dụng, cơ hội việc làm để đưa ra quyết định phù hợp.',
  difficulty: 2,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-choice-11',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-career-choice',
  subject: 'technology',
  prompt: 'Yếu tố "năng lực bản thân" trong chọn nghề được hiểu là gì?',
  options: ['Khả năng, sở trường thực tế của cá nhân đối với công việc', 'Số lượng bạn bè quen biết', 'Sở thích ăn uống', 'Chiều cao và cân nặng'],
  correctAnswer: 'Khả năng, sở trường thực tế của cá nhân đối với công việc',
  explanation: 'Năng lực bản thân là khả năng, sở trường thực tế mà cá nhân có thể đáp ứng yêu cầu của nghề nghiệp.',
  difficulty: 1,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-choice-12',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-career-choice',
  subject: 'technology',
  prompt: 'Bước nào sau đây thuộc quy trình lập kế hoạch nghề nghiệp?',
  options: ['Xác định mục tiêu, tìm hiểu nghề, lập kế hoạch hành động và đánh giá điều chỉnh', 'Chỉ chọn nghề theo cảm tính, không cần các bước khác', 'Bỏ qua việc tìm hiểu thông tin nghề nghiệp', 'Không cần đánh giá lại kế hoạch'],
  correctAnswer: 'Xác định mục tiêu, tìm hiểu nghề, lập kế hoạch hành động và đánh giá điều chỉnh',
  explanation: 'Quy trình lập kế hoạch nghề nghiệp gồm các bước: xác định mục tiêu, tìm hiểu nghề, lập kế hoạch hành động, đánh giá và điều chỉnh.',
  difficulty: 2,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-choice-13',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-career-choice',
  subject: 'technology',
  prompt: 'Sở thích cá nhân có vai trò gì trong việc chọn nghề?',
  options: ['Giúp người lao động gắn bó, hứng thú lâu dài với công việc', 'Không có vai trò gì', 'Chỉ quan trọng bằng với ngoại hình', 'Chỉ áp dụng cho nghề nghệ thuật'],
  correctAnswer: 'Giúp người lao động gắn bó, hứng thú lâu dài với công việc',
  explanation: 'Sở thích phù hợp với nghề nghiệp giúp người lao động có động lực, hứng thú và gắn bó lâu dài với công việc.',
  difficulty: 1,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-choice-14',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-career-choice',
  subject: 'technology',
  prompt: 'Điều kiện gia đình và hoàn cảnh kinh tế nên được xem xét khi chọn nghề như thế nào?',
  options: ['Là một trong các yếu tố cần cân nhắc cùng với sở thích và năng lực', 'Là yếu tố duy nhất quyết định, bỏ qua sở thích và năng lực', 'Không cần xem xét', 'Chỉ quan trọng đối với nghề tự do'],
  correctAnswer: 'Là một trong các yếu tố cần cân nhắc cùng với sở thích và năng lực',
  explanation: 'Điều kiện gia đình là một yếu tố cần cân nhắc, kết hợp cùng sở thích và năng lực bản thân, không phải yếu tố duy nhất.',
  difficulty: 2,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-choice-15',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-career-choice',
  subject: 'technology',
  prompt: 'Vì sao cần đánh giá và điều chỉnh kế hoạch nghề nghiệp theo thời gian?',
  options: ['Vì năng lực, sở thích và thị trường lao động có thể thay đổi', 'Vì kế hoạch ban đầu luôn hoàn hảo, không cần thay đổi', 'Vì không có lý do cần thiết', 'Vì chỉ cần lập kế hoạch một lần duy nhất trong đời'],
  correctAnswer: 'Vì năng lực, sở thích và thị trường lao động có thể thay đổi',
  explanation: 'Kế hoạch nghề nghiệp cần được đánh giá, điều chỉnh định kỳ do năng lực, sở thích cá nhân và thị trường lao động luôn biến đổi.',
  difficulty: 2,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-circuit-6',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-circuit-install',
  subject: 'technology',
  prompt: 'Aptomat (CB - Circuit Breaker) có chức năng chính là gì?',
  options: ['Tự động ngắt mạch điện khi xảy ra quá tải hoặc ngắn mạch', 'Đo điện áp trong mạch', 'Chiếu sáng phòng', 'Tạo ra dòng điện xoay chiều'],
  correctAnswer: 'Tự động ngắt mạch điện khi xảy ra quá tải hoặc ngắn mạch',
  explanation: 'Aptomat (CB) là thiết bị bảo vệ, tự động ngắt mạch điện khi phát hiện quá tải hoặc ngắn mạch, tránh sự cố cháy nổ.',
  difficulty: 1,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-circuit-7',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-circuit-install',
  subject: 'technology',
  prompt: 'Đồng hồ vạn năng (multimeter) được dùng để đo đại lượng nào?',
  options: ['Điện áp, dòng điện và điện trở', 'Nhiệt độ phòng', 'Tốc độ gió', 'Độ ẩm không khí'],
  correctAnswer: 'Điện áp, dòng điện và điện trở',
  explanation: 'Đồng hồ vạn năng là thiết bị đo đa năng, có thể đo điện áp, dòng điện, điện trở và một số đại lượng điện khác.',
  difficulty: 1,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-circuit-8',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-circuit-install',
  subject: 'technology',
  prompt: 'Bút thử điện (voltage tester) dùng để làm gì?',
  options: ['Kiểm tra xem dây dẫn, thiết bị có đang mang điện hay không', 'Đo chiều dài dây điện', 'Cắt dây điện', 'Nối dây điện'],
  correctAnswer: 'Kiểm tra xem dây dẫn, thiết bị có đang mang điện hay không',
  explanation: 'Bút thử điện giúp kiểm tra nhanh xem một điểm, dây dẫn hoặc thiết bị có đang có điện áp hay không, đảm bảo an toàn khi thao tác.',
  difficulty: 1,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-circuit-9',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-circuit-install',
  subject: 'technology',
  prompt: 'Trước khi lắp đặt hoặc sửa chữa mạch điện trong nhà, việc đầu tiên cần làm là gì?',
  options: ['Ngắt nguồn điện tổng (cắt aptomat)', 'Cắm thêm nhiều thiết bị điện', 'Bật hết công tắc đèn', 'Đổ nước lên bảng điện'],
  correctAnswer: 'Ngắt nguồn điện tổng (cắt aptomat)',
  explanation: 'Để đảm bảo an toàn, trước khi lắp đặt hay sửa chữa mạch điện phải ngắt nguồn điện tổng bằng cách cắt aptomat.',
  difficulty: 1,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-circuit-10',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-circuit-install',
  subject: 'technology',
  prompt: 'Trong mạch điện chiếu sáng cơ bản, công tắc thường được mắc ở vị trí nào?',
  options: ['Nối tiếp với dây pha (dây lửa), trước bóng đèn', 'Nối tiếp với dây trung tính', 'Song song với bóng đèn', 'Sau cầu chì và không liên quan đến bóng đèn'],
  correctAnswer: 'Nối tiếp với dây pha (dây lửa), trước bóng đèn',
  explanation: 'Công tắc thường được mắc nối tiếp trên dây pha (dây lửa), trước bóng đèn, để đảm bảo an toàn khi ngắt điện.',
  difficulty: 2,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-circuit-11',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-circuit-install',
  subject: 'technology',
  prompt: 'Dây trung tính (dây nguội) trong hệ thống điện gia đình có màu quy ước phổ biến nào?',
  options: ['Màu xanh dương (lam)', 'Màu đỏ', 'Màu vàng sọc xanh lá', 'Màu đen'],
  correctAnswer: 'Màu xanh dương (lam)',
  explanation: 'Theo quy ước phổ biến, dây trung tính (dây nguội) thường có màu xanh dương (lam) để phân biệt với dây pha.',
  difficulty: 2,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-circuit-12',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-circuit-install',
  subject: 'technology',
  prompt: 'Dây tiếp đất (dây nối đất) trong hệ thống điện có chức năng gì?',
  options: ['Bảo vệ an toàn, dẫn dòng điện rò xuống đất khi có sự cố', 'Tăng thêm ánh sáng cho bóng đèn', 'Giảm hóa đơn tiền điện', 'Làm dây dẫn chính cấp điện cho thiết bị'],
  correctAnswer: 'Bảo vệ an toàn, dẫn dòng điện rò xuống đất khi có sự cố',
  explanation: 'Dây tiếp đất có vai trò bảo vệ an toàn, dẫn dòng điện rò xuống đất khi vỏ thiết bị bị rò điện, tránh gây giật cho người sử dụng.',
  difficulty: 2,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-circuit-13',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-circuit-install',
  subject: 'technology',
  prompt: 'Khi sử dụng đồng hồ vạn năng để đo điện áp xoay chiều, cần chuyển thang đo về vị trí nào?',
  options: ['Thang đo điện áp xoay chiều (ACV)', 'Thang đo điện trở (Ohm)', 'Thang đo dòng điện một chiều (DCA)', 'Thang đo tần số âm thanh'],
  correctAnswer: 'Thang đo điện áp xoay chiều (ACV)',
  explanation: 'Để đo điện áp xoay chiều, cần chuyển đồng hồ vạn năng về đúng thang đo điện áp xoay chiều (ACV) nhằm đọc kết quả chính xác.',
  difficulty: 2,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-circuit-14',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-circuit-install',
  subject: 'technology',
  prompt: 'Nguyên tắc an toàn nào cần tuân thủ khi lắp đặt mạch điện gia đình?',
  options: ['Không làm việc với mạch điện khi tay ướt hoặc đứng trên nền ẩm ướt', 'Có thể sửa điện khi tay còn ướt nếu thao tác nhanh', 'Không cần ngắt nguồn điện khi sửa chữa nhỏ', 'Dùng vật liệu dẫn điện để cách điện'],
  correctAnswer: 'Không làm việc với mạch điện khi tay ướt hoặc đứng trên nền ẩm ướt',
  explanation: 'Nước dẫn điện tốt nên tuyệt đối không thao tác với mạch điện khi tay ướt hoặc đứng trên nền ẩm ướt để tránh bị điện giật.',
  difficulty: 1,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-circuit-15',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-circuit-install',
  subject: 'technology',
  prompt: 'Cầu chì (fuse) trong mạch điện có chức năng gì?',
  options: ['Tự chảy đứt để ngắt mạch khi dòng điện vượt quá giá trị cho phép', 'Tăng cường độ sáng cho bóng đèn', 'Điều chỉnh tốc độ quạt điện', 'Kết nối nhiều ổ cắm với nhau'],
  correctAnswer: 'Tự chảy đứt để ngắt mạch khi dòng điện vượt quá giá trị cho phép',
  explanation: 'Cầu chì là thiết bị bảo vệ, dây chì sẽ nóng chảy và đứt khi dòng điện vượt quá mức cho phép, giúp ngắt mạch bảo vệ thiết bị.',
  difficulty: 1,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-circuit-16',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-circuit-install',
  subject: 'technology',
  prompt: 'Ổ cắm điện trong nhà nên được lắp đặt ở độ cao như thế nào để đảm bảo an toàn cho trẻ nhỏ?',
  options: ['Lắp ở độ cao vừa phải, xa tầm với của trẻ nhỏ', 'Lắp sát mặt sàn nhà', 'Lắp trong tầm với dễ dàng của trẻ', 'Không cần quan tâm đến độ cao'],
  correctAnswer: 'Lắp ở độ cao vừa phải, xa tầm với của trẻ nhỏ',
  explanation: 'Để đảm bảo an toàn, ổ cắm điện nên được lắp ở độ cao hợp lý, tránh xa tầm với của trẻ nhỏ, hạn chế nguy cơ điện giật.',
  difficulty: 1,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-circuit-17',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-circuit-install',
  subject: 'technology',
  prompt: 'Khi kiểm tra một dây dẫn bằng bút thử điện, nếu đèn báo trong bút thử điện sáng thì điều đó cho biết gì?',
  options: ['Dây dẫn đang có điện', 'Dây dẫn bị đứt', 'Dây dẫn không dẫn điện', 'Dây dẫn đã được nối đất'],
  correctAnswer: 'Dây dẫn đang có điện',
  explanation: 'Khi chạm bút thử điện vào dây dẫn, nếu đèn báo sáng lên thì dây đó đang mang điện (dây pha).',
  difficulty: 1,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-circuit-18',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-circuit-install',
  subject: 'technology',
  prompt: 'Sơ đồ nguyên lý mạch điện dùng để thể hiện điều gì?',
  options: ['Mối quan hệ điện giữa các phần tử trong mạch, không quan tâm vị trí lắp đặt thực tế', 'Vị trí lắp đặt thực tế của từng thiết bị trong nhà', 'Kích thước thực tế của dây dẫn', 'Màu sơn của tường nhà'],
  correctAnswer: 'Mối quan hệ điện giữa các phần tử trong mạch, không quan tâm vị trí lắp đặt thực tế',
  explanation: 'Sơ đồ nguyên lý thể hiện mối liên hệ về điện giữa các phần tử trong mạch mà không thể hiện vị trí lắp đặt thực tế, khác với sơ đồ lắp đặt.',
  difficulty: 3,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-circuit-19',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-circuit-install',
  subject: 'technology',
  prompt: 'Khi lắp mạch điện gồm hai công tắc điều khiển độc lập hai bóng đèn, các công tắc và bóng đèn nên được mắc theo kiểu nào?',
  options: ['Mỗi công tắc nối tiếp với một bóng đèn riêng, các nhánh mắc song song với nguồn', 'Tất cả nối tiếp thành một mạch duy nhất', 'Hai công tắc mắc song song với nhau và nối tiếp với cả hai đèn', 'Không cần công tắc nào cả'],
  correctAnswer: 'Mỗi công tắc nối tiếp với một bóng đèn riêng, các nhánh mắc song song với nguồn',
  explanation: 'Để mỗi công tắc điều khiển độc lập một bóng đèn, mỗi cặp công tắc - đèn được mắc nối tiếp thành một nhánh, các nhánh mắc song song với nguồn điện.',
  difficulty: 3,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
{
  id: 'gk-tech-circuit-20',
  type: 'mcq',
  category: 'technology',
  topicId: 'tech-circuit-install',
  subject: 'technology',
  prompt: 'Vì sao không nên sử dụng dây dẫn điện có tiết diện quá nhỏ so với công suất thiết bị tiêu thụ?',
  options: ['Dây dễ bị quá nóng, gây cháy nổ do dòng điện vượt khả năng chịu tải', 'Dây sẽ dẫn điện tốt hơn', 'Không ảnh hưởng gì đến an toàn', 'Giúp tiết kiệm điện năng hơn'],
  correctAnswer: 'Dây dễ bị quá nóng, gây cháy nổ do dòng điện vượt khả năng chịu tải',
  explanation: 'Dây dẫn có tiết diện quá nhỏ so với công suất sử dụng sẽ bị quá tải, sinh nhiệt lớn, dễ gây cháy nổ và mất an toàn.',
  difficulty: 2,
  source: 'GDPT 2018 - Công nghệ lớp 9',
},
