{
  id: 'gk-inf-digital-6',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-digital-world',
  subject: 'informatics',
  prompt: 'Một hệ thống máy tính hoàn chỉnh bao gồm những thành phần chính nào?',
  options: ['Phần cứng, phần mềm và dữ liệu', 'Chỉ có phần cứng', 'Chỉ có phần mềm', 'Bàn phím và chuột'],
  correctAnswer: 'Phần cứng, phần mềm và dữ liệu',
  explanation: 'Hệ thống máy tính gồm ba thành phần chính: phần cứng (thiết bị vật lý), phần mềm (chương trình điều khiển) và dữ liệu (thông tin được xử lý).',
  difficulty: 1,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-digital-7',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-digital-world',
  subject: 'informatics',
  prompt: 'Bộ phận nào của máy tính được coi là "bộ não", chịu trách nhiệm xử lí các lệnh và tính toán?',
  options: ['CPU (bộ xử lí trung tâm)', 'RAM', 'Ổ cứng', 'Màn hình'],
  correctAnswer: 'CPU (bộ xử lí trung tâm)',
  explanation: 'CPU (Central Processing Unit) là bộ phận thực hiện việc xử lí lệnh và tính toán, được ví như "bộ não" của máy tính.',
  difficulty: 1,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-digital-8',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-digital-world',
  subject: 'informatics',
  prompt: 'Đơn vị nhỏ nhất để lưu trữ dữ liệu trong máy tính là gì?',
  options: ['Bit', 'Byte', 'Kilobyte', 'Megabyte'],
  correctAnswer: 'Bit',
  explanation: 'Bit (binary digit) là đơn vị nhỏ nhất, chỉ nhận một trong hai giá trị 0 hoặc 1. 8 bit tạo thành 1 byte.',
  difficulty: 1,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-digital-9',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-digital-world',
  subject: 'informatics',
  prompt: '1 byte tương đương với bao nhiêu bit?',
  options: ['8 bit', '4 bit', '16 bit', '1024 bit'],
  correctAnswer: '8 bit',
  explanation: 'Theo quy ước, 1 byte gồm 8 bit, là đơn vị cơ bản thường dùng để đo dung lượng dữ liệu.',
  difficulty: 1,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-digital-10',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-digital-world',
  subject: 'informatics',
  prompt: 'Ứng dụng nào sau đây KHÔNG phải là ví dụ về ứng dụng công nghệ số trong đời sống hằng ngày?',
  options: ['Viết thư tay gửi qua bưu điện', 'Thanh toán qua ví điện tử', 'Đặt xe qua ứng dụng di động', 'Học trực tuyến qua nền tảng E-learning'],
  correctAnswer: 'Viết thư tay gửi qua bưu điện',
  explanation: 'Viết thư tay là hình thức truyền thống, không sử dụng công nghệ số; các phương án còn lại đều là ứng dụng số hoá trong đời sống.',
  difficulty: 1,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-digital-11',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-digital-world',
  subject: 'informatics',
  prompt: 'Phần mềm hệ thống có vai trò gì trong máy tính?',
  options: ['Quản lí và điều khiển hoạt động của phần cứng', 'Chỉ dùng để giải trí', 'Chỉ dùng để soạn thảo văn bản', 'Chỉ lưu trữ dữ liệu cá nhân'],
  correctAnswer: 'Quản lí và điều khiển hoạt động của phần cứng',
  explanation: 'Phần mềm hệ thống (như hệ điều hành) có nhiệm vụ quản lí, điều phối hoạt động của phần cứng và các phần mềm ứng dụng khác.',
  difficulty: 2,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-digital-12',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-digital-world',
  subject: 'informatics',
  prompt: 'Trong các đơn vị đo dung lượng dữ liệu sau, đơn vị nào lớn nhất?',
  options: ['Gigabyte (GB)', 'Byte', 'Kilobyte (KB)', 'Megabyte (MB)'],
  correctAnswer: 'Gigabyte (GB)',
  explanation: 'Thứ tự tăng dần dung lượng là: Byte < Kilobyte < Megabyte < Gigabyte, nên GB là đơn vị lớn nhất trong các phương án.',
  difficulty: 1,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-digital-13',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-digital-world',
  subject: 'informatics',
  prompt: 'Thiết bị nào sau đây thuộc nhóm thiết bị vào (input) của máy tính?',
  options: ['Bàn phím', 'Màn hình', 'Loa', 'Máy in'],
  correctAnswer: 'Bàn phím',
  explanation: 'Bàn phím là thiết bị vào, dùng để nhập dữ liệu và lệnh vào máy tính; màn hình, loa, máy in là thiết bị ra.',
  difficulty: 1,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-digital-14',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-digital-world',
  subject: 'informatics',
  prompt: 'Dữ liệu trong máy tính được biểu diễn dưới dạng nào?',
  options: ['Dãy các số nhị phân (0 và 1)', 'Dãy các chữ cái Latinh', 'Dãy các số thập phân', 'Hình ảnh trực tiếp'],
  correctAnswer: 'Dãy các số nhị phân (0 và 1)',
  explanation: 'Mọi dữ liệu (văn bản, hình ảnh, âm thanh) khi lưu trữ và xử lí trong máy tính đều được mã hoá thành dãy bit nhị phân 0 và 1.',
  difficulty: 2,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-digital-15',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-digital-world',
  subject: 'informatics',
  prompt: 'Ứng dụng công nghệ số nào giúp người dân theo dõi sức khoẻ và đặt lịch khám bệnh trực tuyến?',
  options: ['Ứng dụng y tế điện tử', 'Ứng dụng chỉnh sửa ảnh', 'Ứng dụng nghe nhạc', 'Ứng dụng bản đồ offline'],
  correctAnswer: 'Ứng dụng y tế điện tử',
  explanation: 'Các ứng dụng y tế điện tử (telehealth) cho phép người dùng đặt lịch khám, tra cứu hồ sơ và theo dõi sức khoẻ trực tuyến.',
  difficulty: 1,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-data-6',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-data-manage',
  subject: 'informatics',
  prompt: 'Khi đánh giá độ tin cậy của một thông tin trên Internet, yếu tố nào sau đây quan trọng nhất cần xem xét?',
  options: ['Nguồn gốc và tác giả của thông tin', 'Màu sắc của trang web', 'Số lượng hình ảnh minh hoạ', 'Độ dài của bài viết'],
  correctAnswer: 'Nguồn gốc và tác giả của thông tin',
  explanation: 'Để đánh giá độ tin cậy, cần kiểm tra nguồn gốc, tác giả, và tính xác thực của thông tin thay vì hình thức trình bày.',
  difficulty: 1,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-data-7',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-data-manage',
  subject: 'informatics',
  prompt: 'Dịch vụ lưu trữ đám mây (cloud storage) cho phép người dùng làm gì?',
  options: ['Lưu trữ và truy cập dữ liệu qua Internet từ nhiều thiết bị', 'Chỉ lưu trữ dữ liệu trên một máy tính duy nhất', 'Xoá dữ liệu vĩnh viễn khỏi Internet', 'In tài liệu trực tiếp từ xa'],
  correctAnswer: 'Lưu trữ và truy cập dữ liệu qua Internet từ nhiều thiết bị',
  explanation: 'Lưu trữ đám mây cho phép người dùng lưu và truy cập dữ liệu từ bất kì thiết bị nào có kết nối Internet, ví dụ Google Drive, OneDrive.',
  difficulty: 1,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-data-8',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-data-manage',
  subject: 'informatics',
  prompt: 'Công cụ nào sau đây thường được dùng để nhiều người cùng chỉnh sửa một tài liệu trực tuyến theo thời gian thực?',
  options: ['Google Docs', 'Notepad', 'Máy tính bỏ túi', 'Trình duyệt ảnh offline'],
  correctAnswer: 'Google Docs',
  explanation: 'Google Docs là công cụ cộng tác trực tuyến cho phép nhiều người cùng soạn thảo, chỉnh sửa tài liệu đồng thời và theo dõi thay đổi.',
  difficulty: 1,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-data-9',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-data-manage',
  subject: 'informatics',
  prompt: 'Công cụ tìm kiếm (search engine) có chức năng chính là gì?',
  options: ['Tìm kiếm và hiển thị thông tin liên quan trên Internet', 'Chỉ dùng để lưu trữ email', 'Chỉ dùng để chỉnh sửa video', 'Chỉ dùng để nghe nhạc trực tuyến'],
  correctAnswer: 'Tìm kiếm và hiển thị thông tin liên quan trên Internet',
  explanation: 'Công cụ tìm kiếm như Google, Bing giúp người dùng tra cứu và tìm thông tin phù hợp với từ khoá trên Internet.',
  difficulty: 1,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-data-10',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-data-manage',
  subject: 'informatics',
  prompt: 'Việc tổ chức dữ liệu thành các thư mục (folder) có tên rõ ràng, phân cấp hợp lí mang lại lợi ích gì?',
  options: ['Dễ dàng tìm kiếm và quản lí dữ liệu', 'Làm giảm dung lượng ổ đĩa', 'Tăng tốc độ xử lí của CPU', 'Tự động sao lưu dữ liệu lên mạng'],
  correctAnswer: 'Dễ dàng tìm kiếm và quản lí dữ liệu',
  explanation: 'Tổ chức dữ liệu khoa học, đặt tên thư mục rõ ràng giúp tìm kiếm, truy xuất và quản lí tệp tin nhanh chóng, hiệu quả hơn.',
  difficulty: 1,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-data-11',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-data-manage',
  subject: 'informatics',
  prompt: 'Khi đọc một bài báo trực tuyến không ghi rõ nguồn và tác giả, người dùng nên làm gì?',
  options: ['Kiểm tra chéo thông tin với các nguồn uy tín khác trước khi tin', 'Chia sẻ ngay lập tức cho bạn bè', 'Tin tưởng hoàn toàn vì đã đọc trên mạng', 'Bỏ qua việc kiểm chứng vì mất thời gian'],
  correctAnswer: 'Kiểm tra chéo thông tin với các nguồn uy tín khác trước khi tin',
  explanation: 'Thông tin không rõ nguồn gốc cần được kiểm chứng qua nhiều nguồn uy tín khác để tránh tin giả (fake news).',
  difficulty: 2,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-data-12',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-data-manage',
  subject: 'informatics',
  prompt: 'Ưu điểm nổi bật của việc lưu trữ dữ liệu trên đám mây so với lưu trữ cục bộ là gì?',
  options: ['Có thể truy cập dữ liệu từ nhiều thiết bị, nhiều nơi khác nhau', 'Không bao giờ bị mất dữ liệu', 'Không cần kết nối Internet', 'Dung lượng luôn miễn phí và không giới hạn'],
  correctAnswer: 'Có thể truy cập dữ liệu từ nhiều thiết bị, nhiều nơi khác nhau',
  explanation: 'Lưu trữ đám mây cho phép truy cập linh hoạt từ nhiều thiết bị có kết nối Internet, khác với lưu trữ cục bộ chỉ giới hạn trên một máy.',
  difficulty: 2,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-data-13',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-data-manage',
  subject: 'informatics',
  prompt: 'Công cụ họp trực tuyến nào sau đây được sử dụng phổ biến để học tập và làm việc từ xa?',
  options: ['Microsoft Teams', 'Microsoft Paint', 'Adobe Photoshop', 'Windows Media Player'],
  correctAnswer: 'Microsoft Teams',
  explanation: 'Microsoft Teams là nền tảng họp trực tuyến, cộng tác nhóm phổ biến trong học tập và công việc từ xa.',
  difficulty: 1,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-data-14',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-data-manage',
  subject: 'informatics',
  prompt: 'Khi tìm kiếm thông tin trên công cụ tìm kiếm, sử dụng từ khoá như thế nào sẽ cho kết quả chính xác hơn?',
  options: ['Từ khoá ngắn gọn, cụ thể, đúng trọng tâm', 'Từ khoá càng dài càng tốt, không cần liên quan', 'Chỉ dùng một kí tự bất kì', 'Không cần dùng từ khoá'],
  correctAnswer: 'Từ khoá ngắn gọn, cụ thể, đúng trọng tâm',
  explanation: 'Từ khoá cụ thể, ngắn gọn và đúng trọng tâm giúp công cụ tìm kiếm trả về kết quả chính xác và phù hợp hơn.',
  difficulty: 2,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-data-15',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-data-manage',
  subject: 'informatics',
  prompt: 'Việc đặt tên tệp và thư mục theo quy tắc thống nhất (ví dụ: có ngày tháng, chủ đề) giúp ích gì?',
  options: ['Quản lí, sắp xếp và tìm kiếm dữ liệu hiệu quả hơn', 'Tăng tốc độ mạng Internet', 'Giảm dung lượng tệp tự động', 'Ngăn chặn virus xâm nhập'],
  correctAnswer: 'Quản lí, sắp xếp và tìm kiếm dữ liệu hiệu quả hơn',
  explanation: 'Đặt tên tệp/thư mục theo quy tắc rõ ràng, nhất quán giúp việc quản lí và tìm kiếm dữ liệu trở nên khoa học và nhanh chóng hơn.',
  difficulty: 1,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-ethics-6',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-ethics-law',
  subject: 'informatics',
  prompt: 'Việc sao chép và sử dụng phần mềm có bản quyền mà không được phép của tác giả được gọi là gì?',
  options: ['Vi phạm bản quyền phần mềm', 'Sử dụng phần mềm hợp pháp', 'Chia sẻ phần mềm miễn phí', 'Cập nhật phần mềm'],
  correctAnswer: 'Vi phạm bản quyền phần mềm',
  explanation: 'Sao chép, phân phối phần mềm có bản quyền mà không được phép của chủ sở hữu là hành vi vi phạm bản quyền, có thể bị xử lí theo pháp luật.',
  difficulty: 1,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-ethics-7',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-ethics-law',
  subject: 'informatics',
  prompt: 'Hành vi nào sau đây thể hiện phép lịch sự (digital etiquette) khi giao tiếp trực tuyến?',
  options: ['Sử dụng ngôn từ lịch sự, tôn trọng người khác trong bình luận', 'Viết bình luận xúc phạm người khác', 'Gửi tin nhắn spam liên tục', 'Đăng thông tin sai sự thật về người khác'],
  correctAnswer: 'Sử dụng ngôn từ lịch sự, tôn trọng người khác trong bình luận',
  explanation: 'Ứng xử văn minh trên mạng đòi hỏi dùng ngôn từ lịch sự, tôn trọng người khác khi giao tiếp, bình luận trực tuyến.',
  difficulty: 1,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-ethics-8',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-ethics-law',
  subject: 'informatics',
  prompt: 'Để bảo vệ thông tin cá nhân khi sử dụng mạng xã hội, học sinh nên làm gì?',
  options: ['Hạn chế chia sẻ thông tin nhạy cảm và đặt chế độ riêng tư phù hợp', 'Công khai số điện thoại và địa chỉ nhà cho mọi người xem', 'Chia sẻ mật khẩu tài khoản cho bạn bè', 'Đăng ảnh chứng minh nhân dân lên mạng'],
  correctAnswer: 'Hạn chế chia sẻ thông tin nhạy cảm và đặt chế độ riêng tư phù hợp',
  explanation: 'Bảo vệ thông tin cá nhân đòi hỏi hạn chế chia sẻ dữ liệu nhạy cảm và thiết lập chế độ riêng tư trên các nền tảng mạng xã hội.',
  difficulty: 1,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-ethics-9',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-ethics-law',
  subject: 'informatics',
  prompt: 'Hành vi bắt nạt trực tuyến (cyberbullying) là gì?',
  options: ['Sử dụng công nghệ để đe doạ, xúc phạm, quấy rối người khác', 'Kết bạn với người mới trên mạng xã hội', 'Chia sẻ bài viết học tập hữu ích', 'Bình luận khen ngợi bạn bè'],
  correctAnswer: 'Sử dụng công nghệ để đe doạ, xúc phạm, quấy rối người khác',
  explanation: 'Bắt nạt trực tuyến là hành vi sử dụng thiết bị số, mạng xã hội để đe doạ, xúc phạm hoặc quấy rối người khác, gây tổn hại tinh thần nạn nhân.',
  difficulty: 1,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-ethics-10',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-ethics-law',
  subject: 'informatics',
  prompt: 'Luật An ninh mạng của Việt Nam được Quốc hội thông qua vào năm nào?',
  options: ['2018', '2015', '2020', '2010'],
  correctAnswer: '2018',
  explanation: 'Luật An ninh mạng được Quốc hội nước Cộng hòa xã hội chủ nghĩa Việt Nam thông qua ngày 12/6/2018 và có hiệu lực từ 01/01/2019.',
  difficulty: 2,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-ethics-11',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-ethics-law',
  subject: 'informatics',
  prompt: 'Theo quy định pháp luật, hành vi nào sau đây là vi phạm khi sử dụng không gian mạng?',
  options: ['Đăng tải thông tin sai sự thật gây hoang mang dư luận', 'Học tập trực tuyến qua các khoá học chính thống', 'Sử dụng phần mềm có bản quyền hợp pháp', 'Tham gia diễn đàn học tập lành mạnh'],
  correctAnswer: 'Đăng tải thông tin sai sự thật gây hoang mang dư luận',
  explanation: 'Luật An ninh mạng nghiêm cấm hành vi đăng tải thông tin sai sự thật, xuyên tạc gây hoang mang trong nhân dân.',
  difficulty: 2,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-ethics-12',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-ethics-law',
  subject: 'informatics',
  prompt: 'Khi bị bắt nạt trực tuyến, học sinh nên xử lí như thế nào?',
  options: ['Lưu lại bằng chứng và báo với người lớn, thầy cô đáng tin cậy', 'Im lặng chịu đựng một mình', 'Đáp trả bằng lời lẽ xúc phạm tương tự', 'Xoá hết toàn bộ tài khoản mạng xã hội ngay lập tức'],
  correctAnswer: 'Lưu lại bằng chứng và báo với người lớn, thầy cô đáng tin cậy',
  explanation: 'Khi bị bắt nạt trực tuyến, cần giữ lại bằng chứng (ảnh chụp màn hình) và thông báo cho người lớn, thầy cô hoặc cơ quan chức năng để được hỗ trợ.',
  difficulty: 2,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-ethics-13',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-ethics-law',
  subject: 'informatics',
  prompt: 'Phần mềm "dùng thử miễn phí" (trial/shareware) có bản quyền cho phép người dùng làm gì?',
  options: ['Sử dụng có giới hạn về thời gian hoặc tính năng theo quy định của nhà phát triển', 'Sao chép và bán lại tự do', 'Chỉnh sửa mã nguồn và phân phối lại', 'Sử dụng vĩnh viễn không giới hạn tính năng'],
  correctAnswer: 'Sử dụng có giới hạn về thời gian hoặc tính năng theo quy định của nhà phát triển',
  explanation: 'Phần mềm dùng thử cho phép sử dụng trong một khoảng thời gian hoặc với tính năng giới hạn, người dùng cần mua bản quyền để sử dụng đầy đủ.',
  difficulty: 2,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-ethics-14',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-ethics-law',
  subject: 'informatics',
  prompt: 'Việc chia sẻ mật khẩu tài khoản cá nhân cho người khác có thể dẫn đến hậu quả gì?',
  options: ['Bị lộ thông tin cá nhân, tài khoản bị chiếm đoạt hoặc lạm dụng', 'Giúp tài khoản an toàn hơn', 'Không có ảnh hưởng gì', 'Tăng tốc độ đăng nhập'],
  correctAnswer: 'Bị lộ thông tin cá nhân, tài khoản bị chiếm đoạt hoặc lạm dụng',
  explanation: 'Chia sẻ mật khẩu làm tăng nguy cơ bị lộ thông tin cá nhân, tài khoản có thể bị người khác chiếm đoạt hoặc sử dụng sai mục đích.',
  difficulty: 1,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-ethics-15',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-ethics-law',
  subject: 'informatics',
  prompt: 'Nguyên tắc cơ bản của ứng xử văn minh trên mạng (netiquette) là gì?',
  options: ['Tôn trọng người khác như khi giao tiếp trực tiếp ngoài đời', 'Có thể nói bất cứ điều gì vì không ai biết danh tính thật', 'Chỉ cần tuân thủ khi có người giám sát', 'Không cần áp dụng quy tắc nào khi online'],
  correctAnswer: 'Tôn trọng người khác như khi giao tiếp trực tiếp ngoài đời',
  explanation: 'Netiquette yêu cầu người dùng ứng xử tôn trọng, lịch sự trên không gian mạng tương tự như trong giao tiếp trực tiếp ngoài đời thực.',
  difficulty: 2,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-tools-6',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-digital-tools',
  subject: 'informatics',
  prompt: 'Hàm nào trong bảng tính dùng để kiểm tra một điều kiện và trả về một trong hai giá trị tùy theo điều kiện đúng hay sai?',
  options: ['IF', 'SUM', 'COUNT', 'AVERAGE'],
  correctAnswer: 'IF',
  explanation: 'Hàm IF có cú pháp =IF(điều kiện, giá trị nếu đúng, giá trị nếu sai), dùng để kiểm tra điều kiện logic và trả về kết quả tương ứng.',
  difficulty: 1,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-tools-7',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-digital-tools',
  subject: 'informatics',
  prompt: 'Hàm COUNTIF trong bảng tính dùng để làm gì?',
  options: ['Đếm số ô thỏa mãn một điều kiện cho trước', 'Tính tổng các giá trị trong vùng dữ liệu', 'Tính giá trị trung bình', 'Sắp xếp dữ liệu tăng dần'],
  correctAnswer: 'Đếm số ô thỏa mãn một điều kiện cho trước',
  explanation: 'Hàm COUNTIF(vùng, điều kiện) đếm số lượng ô trong vùng dữ liệu thỏa mãn điều kiện được chỉ định.',
  difficulty: 1,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-tools-8',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-digital-tools',
  subject: 'informatics',
  prompt: 'Hàm SUMIF trong bảng tính có chức năng gì?',
  options: ['Tính tổng các giá trị thỏa mãn một điều kiện cho trước', 'Đếm số ô trống', 'Tìm giá trị lớn nhất', 'Tìm giá trị nhỏ nhất'],
  correctAnswer: 'Tính tổng các giá trị thỏa mãn một điều kiện cho trước',
  explanation: 'Hàm SUMIF(vùng điều kiện, điều kiện, vùng tính tổng) tính tổng các giá trị trong vùng dữ liệu thỏa mãn điều kiện chỉ định.',
  difficulty: 2,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-tools-9',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-digital-tools',
  subject: 'informatics',
  prompt: 'Chức năng "Data Validation" (kiểm tra dữ liệu hợp lệ) trong bảng tính dùng để làm gì?',
  options: ['Giới hạn và kiểm soát loại dữ liệu được nhập vào ô tính', 'Tự động tính tổng toàn bộ bảng', 'Xoá dữ liệu không cần thiết', 'Định dạng màu sắc cho ô tính'],
  correctAnswer: 'Giới hạn và kiểm soát loại dữ liệu được nhập vào ô tính',
  explanation: 'Data Validation giúp thiết lập quy tắc kiểm soát dữ liệu nhập vào, ví dụ chỉ cho phép số trong khoảng nhất định hoặc chọn từ danh sách có sẵn.',
  difficulty: 2,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-tools-10',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-digital-tools',
  subject: 'informatics',
  prompt: 'Trong PowerPoint, "Animation" (hiệu ứng động) được áp dụng cho đối tượng nào?',
  options: ['Các đối tượng trên một trang chiếu (văn bản, hình ảnh)', 'Toàn bộ tệp trình chiếu', 'Chỉ áp dụng cho tiêu đề bài thuyết trình', 'Chỉ áp dụng cho phông chữ'],
  correctAnswer: 'Các đối tượng trên một trang chiếu (văn bản, hình ảnh)',
  explanation: 'Animation là hiệu ứng chuyển động áp dụng cho từng đối tượng (văn bản, hình ảnh, biểu đồ...) trong một trang chiếu.',
  difficulty: 1,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-tools-11',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-digital-tools',
  subject: 'informatics',
  prompt: 'Trong PowerPoint, "Transition" (hiệu ứng chuyển tiếp) áp dụng cho phạm vi nào?',
  options: ['Giữa hai trang chiếu liên tiếp', 'Giữa các từ trong một câu', 'Giữa các đối tượng trong cùng một trang chiếu', 'Chỉ áp dụng cho hình nền'],
  correctAnswer: 'Giữa hai trang chiếu liên tiếp',
  explanation: 'Transition là hiệu ứng chuyển động khi chuyển từ trang chiếu này sang trang chiếu tiếp theo, khác với Animation áp dụng cho đối tượng trong cùng trang.',
  difficulty: 1,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-tools-12',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-digital-tools',
  subject: 'informatics',
  prompt: 'Trong chỉnh sửa video cơ bản, "cắt" (trim/cut) một đoạn video có nghĩa là gì?',
  options: ['Loại bỏ phần không cần thiết ở đầu, cuối hoặc giữa đoạn video', 'Tăng độ phân giải của video', 'Thêm nhạc nền vào video', 'Xuất video sang định dạng khác'],
  correctAnswer: 'Loại bỏ phần không cần thiết ở đầu, cuối hoặc giữa đoạn video',
  explanation: 'Cắt (trim/cut) là thao tác loại bỏ các đoạn không cần thiết trong video để video ngắn gọn, súc tích hơn.',
  difficulty: 1,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-tools-13',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-digital-tools',
  subject: 'informatics',
  prompt: 'Công thức =IF(A1>=5,"Đạt","Chưa đạt") trong bảng tính trả về kết quả gì nếu ô A1 chứa giá trị 7?',
  options: ['Đạt', 'Chưa đạt', 'TRUE', 'FALSE'],
  correctAnswer: 'Đạt',
  explanation: 'Vì A1 = 7 lớn hơn hoặc bằng 5, điều kiện đúng nên hàm IF trả về giá trị "Đạt".',
  difficulty: 2,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-tools-14',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-digital-tools',
  subject: 'informatics',
  prompt: 'Để đếm số học sinh có điểm từ 8 trở lên trong vùng dữ liệu B2:B20, công thức nào sau đây là đúng?',
  options: ['=COUNTIF(B2:B20,">=8")', '=SUMIF(B2:B20,">=8")', '=SUM(B2:B20,">=8")', '=IF(B2:B20>=8)'],
  correctAnswer: '=COUNTIF(B2:B20,">=8")',
  explanation: 'COUNTIF(vùng, điều kiện) dùng để đếm số ô thỏa mãn điều kiện, ở đây là điều kiện điểm số lớn hơn hoặc bằng 8.',
  difficulty: 2,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-tools-15',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-digital-tools',
  subject: 'informatics',
  prompt: 'Khi làm bài thuyết trình, việc lạm dụng quá nhiều hiệu ứng Animation và Transition có thể gây ra vấn đề gì?',
  options: ['Gây rối mắt, phân tán sự chú ý của người xem khỏi nội dung chính', 'Làm bài thuyết trình chuyên nghiệp hơn', 'Giúp tiết kiệm thời gian trình bày', 'Tăng độ tin cậy của nội dung'],
  correctAnswer: 'Gây rối mắt, phân tán sự chú ý của người xem khỏi nội dung chính',
  explanation: 'Sử dụng quá nhiều hiệu ứng động có thể khiến người xem mất tập trung vào nội dung chính, làm giảm hiệu quả truyền đạt thông tin.',
  difficulty: 2,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-tools-16',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-digital-tools',
  subject: 'informatics',
  prompt: 'Trong phần mềm chỉnh sửa video, "timeline" (dòng thời gian) dùng để làm gì?',
  options: ['Sắp xếp và quản lí thứ tự các đoạn video, âm thanh theo thời gian', 'Chỉ để xem trước video ở độ phân giải cao', 'Lưu trữ video lên đám mây', 'Chuyển đổi định dạng video'],
  correctAnswer: 'Sắp xếp và quản lí thứ tự các đoạn video, âm thanh theo thời gian',
  explanation: 'Timeline là nơi người dùng sắp xếp các đoạn video, hình ảnh, âm thanh theo trình tự thời gian để tạo thành sản phẩm video hoàn chỉnh.',
  difficulty: 2,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-tools-17',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-digital-tools',
  subject: 'informatics',
  prompt: 'Chức năng nào trong bảng tính giúp giới hạn danh sách các giá trị hợp lệ được nhập vào một ô (ví dụ chỉ chọn "Nam" hoặc "Nữ")?',
  options: ['Data Validation với danh sách (List)', 'Conditional Formatting', 'Freeze Panes', 'AutoSum'],
  correctAnswer: 'Data Validation với danh sách (List)',
  explanation: 'Data Validation cho phép thiết lập danh sách các giá trị hợp lệ (List), giúp người dùng chỉ chọn từ các lựa chọn cho sẵn, tránh nhập sai.',
  difficulty: 2,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-tools-18',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-digital-tools',
  subject: 'informatics',
  prompt: 'Trong PowerPoint, để trang chiếu tự động chuyển sang trang tiếp theo sau một khoảng thời gian mà không cần nhấp chuột, cần thiết lập ở đâu?',
  options: ['Transition - Advance Slide (After)', 'Animation - Entrance', 'Design - Themes', 'Insert - Picture'],
  correctAnswer: 'Transition - Advance Slide (After)',
  explanation: 'Trong tab Transitions, mục "Advance Slide - After" cho phép thiết lập thời gian để trang chiếu tự động chuyển mà không cần thao tác thủ công.',
  difficulty: 2,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-tools-19',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-digital-tools',
  subject: 'informatics',
  prompt: 'Công thức =SUMIF(C2:C10,"Toán",D2:D10) thực hiện điều gì?',
  options: ['Tính tổng các giá trị trong D2:D10 tương ứng với các ô có giá trị "Toán" trong C2:C10', 'Đếm số ô có giá trị "Toán" trong C2:C10', 'Tính trung bình cộng của D2:D10', 'Tìm giá trị lớn nhất trong D2:D10'],
  correctAnswer: 'Tính tổng các giá trị trong D2:D10 tương ứng với các ô có giá trị "Toán" trong C2:C10',
  explanation: 'SUMIF(vùng điều kiện, điều kiện, vùng tính tổng) sẽ cộng các giá trị trong vùng tính tổng ứng với các dòng thỏa mãn điều kiện ở vùng điều kiện.',
  difficulty: 3,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-tools-20',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-digital-tools',
  subject: 'informatics',
  prompt: 'Khi xuất bản video sau khi chỉnh sửa, định dạng phổ biến thường được sử dụng là gì?',
  options: ['MP4', 'DOCX', 'XLSX', 'PPTX'],
  correctAnswer: 'MP4',
  explanation: 'MP4 là định dạng video phổ biến, được hỗ trợ rộng rãi trên nhiều thiết bị và nền tảng khi xuất bản sản phẩm video.',
  difficulty: 1,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-algo-6',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-algorithm',
  subject: 'informatics',
  prompt: 'Thuật toán là gì?',
  options: ['Một dãy hữu hạn các bước để giải quyết một vấn đề cụ thể', 'Một loại ngôn ngữ lập trình', 'Một thiết bị phần cứng máy tính', 'Một loại virus máy tính'],
  correctAnswer: 'Một dãy hữu hạn các bước để giải quyết một vấn đề cụ thể',
  explanation: 'Thuật toán là một dãy hữu hạn các bước, thao tác được sắp xếp theo trình tự xác định để giải quyết một vấn đề hoặc bài toán cụ thể.',
  difficulty: 1,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-algo-7',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-algorithm',
  subject: 'informatics',
  prompt: 'Sơ đồ khối (flowchart) được dùng để làm gì?',
  options: ['Biểu diễn trực quan các bước của một thuật toán', 'Lưu trữ dữ liệu của chương trình', 'Chạy chương trình trực tiếp', 'Kiểm tra lỗi phần cứng máy tính'],
  correctAnswer: 'Biểu diễn trực quan các bước của một thuật toán',
  explanation: 'Sơ đồ khối là công cụ trực quan sử dụng các hình khối và mũi tên để mô tả trình tự các bước thực hiện của thuật toán.',
  difficulty: 1,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-algo-8',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-algorithm',
  subject: 'informatics',
  prompt: 'Trong sơ đồ khối, hình thoi (diamond) thường biểu diễn thao tác nào?',
  options: ['Kiểm tra điều kiện (rẽ nhánh)', 'Bắt đầu hoặc kết thúc chương trình', 'Nhập/xuất dữ liệu', 'Xử lí, tính toán'],
  correctAnswer: 'Kiểm tra điều kiện (rẽ nhánh)',
  explanation: 'Hình thoi trong sơ đồ khối biểu diễn bước kiểm tra điều kiện, dẫn đến các nhánh rẽ khác nhau tùy theo điều kiện đúng hay sai.',
  difficulty: 2,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-algo-9',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-algorithm',
  subject: 'informatics',
  prompt: 'Trong lập trình, "biến" (variable) được dùng để làm gì?',
  options: ['Lưu trữ giá trị dữ liệu có thể thay đổi trong quá trình chạy chương trình', 'Chỉ hiển thị văn bản cố định', 'Chỉ dùng để đặt tên chương trình', 'Chỉ dùng để vẽ hình'],
  correctAnswer: 'Lưu trữ giá trị dữ liệu có thể thay đổi trong quá trình chạy chương trình',
  explanation: 'Biến là một vùng nhớ được đặt tên, dùng để lưu trữ dữ liệu mà giá trị của nó có thể thay đổi trong quá trình thực thi chương trình.',
  difficulty: 1,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-algo-10',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-algorithm',
  subject: 'informatics',
  prompt: 'Cấu trúc lặp (loop) trong lập trình được sử dụng khi nào?',
  options: ['Khi cần thực hiện lặp lại một khối lệnh nhiều lần', 'Khi chỉ cần thực hiện một lệnh duy nhất', 'Khi cần kết thúc chương trình ngay lập tức', 'Khi không có dữ liệu đầu vào'],
  correctAnswer: 'Khi cần thực hiện lặp lại một khối lệnh nhiều lần',
  explanation: 'Cấu trúc lặp (for, while) cho phép thực hiện lặp đi lặp lại một khối lệnh theo số lần xác định hoặc theo điều kiện.',
  difficulty: 1,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-algo-11',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-algorithm',
  subject: 'informatics',
  prompt: 'Trong Python, câu lệnh nào dùng để kiểm tra điều kiện và thực hiện rẽ nhánh?',
  options: ['if', 'for', 'print', 'def'],
  correctAnswer: 'if',
  explanation: 'Câu lệnh if trong Python dùng để kiểm tra một điều kiện, nếu đúng thì thực hiện khối lệnh tương ứng, thể hiện cấu trúc rẽ nhánh.',
  difficulty: 1,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-algo-12',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-algorithm',
  subject: 'informatics',
  prompt: 'Trong Python, vòng lặp "for i in range(5):" sẽ lặp lại bao nhiêu lần?',
  options: ['5 lần', '4 lần', '6 lần', 'Vô hạn lần'],
  correctAnswer: '5 lần',
  explanation: 'range(5) tạo ra dãy số từ 0 đến 4 (gồm 5 giá trị: 0,1,2,3,4), do đó vòng lặp for sẽ chạy 5 lần.',
  difficulty: 2,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-algo-13',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-algorithm',
  subject: 'informatics',
  prompt: 'Trong Scratch, khối lệnh nào được dùng để lặp lại một hành động một số lần nhất định?',
  options: ['repeat', 'if then', 'wait', 'broadcast'],
  correctAnswer: 'repeat',
  explanation: 'Khối lệnh "repeat (n)" trong Scratch dùng để lặp lại các khối lệnh bên trong nó n lần.',
  difficulty: 1,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-algo-14',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-algorithm',
  subject: 'informatics',
  prompt: 'Hàm (function) trong lập trình có vai trò gì?',
  options: ['Đóng gói một đoạn mã để tái sử dụng nhiều lần', 'Chỉ dùng để in ra màn hình một lần duy nhất', 'Xoá toàn bộ chương trình', 'Chỉ dùng trong ngôn ngữ Scratch'],
  correctAnswer: 'Đóng gói một đoạn mã để tái sử dụng nhiều lần',
  explanation: 'Hàm là một khối lệnh được đặt tên, cho phép đóng gói logic xử lí để có thể gọi lại và tái sử dụng nhiều lần trong chương trình.',
  difficulty: 2,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-algo-15',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-algorithm',
  subject: 'informatics',
  prompt: 'Ba cấu trúc điều khiển cơ bản trong lập trình là gì?',
  options: ['Tuần tự, rẽ nhánh, lặp', 'Biến, hàm, mảng', 'Nhập, xử lí, xuất', 'Bit, byte, kilobyte'],
  correctAnswer: 'Tuần tự, rẽ nhánh, lặp',
  explanation: 'Ba cấu trúc điều khiển cơ bản của lập trình có cấu trúc là: tuần tự (sequence), rẽ nhánh (selection) và lặp (repetition/loop).',
  difficulty: 2,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-algo-16',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-algorithm',
  subject: 'informatics',
  prompt: 'Trong sơ đồ khối, hình chữ nhật thường biểu diễn thao tác nào?',
  options: ['Xử lí, tính toán', 'Bắt đầu/kết thúc chương trình', 'Kiểm tra điều kiện', 'Nhập dữ liệu từ bàn phím'],
  correctAnswer: 'Xử lí, tính toán',
  explanation: 'Hình chữ nhật trong sơ đồ khối thường biểu diễn các bước xử lí, tính toán trong thuật toán.',
  difficulty: 2,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-algo-17',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-algorithm',
  subject: 'informatics',
  prompt: 'Đoạn mã Python "x = 5\\ny = 10\\nprint(x + y)" sẽ in ra kết quả gì?',
  options: ['15', '510', '5', '10'],
  correctAnswer: '15',
  explanation: 'Biến x nhận giá trị 5, y nhận giá trị 10, phép toán x + y cho kết quả là 15, và lệnh print sẽ in ra giá trị này.',
  difficulty: 2,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-algo-18',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-algorithm',
  subject: 'informatics',
  prompt: 'Một thuật toán tốt cần có những đặc điểm nào?',
  options: ['Tính xác định, tính dừng và tính đúng đắn', 'Càng dài càng tốt', 'Không cần đầu vào hay đầu ra', 'Chỉ chạy được trên một loại máy tính'],
  correctAnswer: 'Tính xác định, tính dừng và tính đúng đắn',
  explanation: 'Một thuật toán tốt cần đảm bảo tính xác định (rõ ràng từng bước), tính dừng (kết thúc sau hữu hạn bước) và tính đúng đắn (cho kết quả đúng).',
  difficulty: 3,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-algo-19',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-algorithm',
  subject: 'informatics',
  prompt: 'Trong Scratch, khối lệnh "if...then...else" dùng để làm gì?',
  options: ['Rẽ nhánh: thực hiện một trong hai nhóm lệnh tùy theo điều kiện', 'Lặp lại một hành động vô hạn lần', 'Di chuyển nhân vật trên sân khấu', 'Phát ra âm thanh khi nhấn phím'],
  correctAnswer: 'Rẽ nhánh: thực hiện một trong hai nhóm lệnh tùy theo điều kiện',
  explanation: 'Khối "if...then...else" trong Scratch cho phép chương trình rẽ nhánh, thực hiện nhóm lệnh này nếu điều kiện đúng, hoặc nhóm lệnh khác nếu điều kiện sai.',
  difficulty: 2,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-algo-20',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-algorithm',
  subject: 'informatics',
  prompt: 'Trong Python, để định nghĩa một hàm mới, ta sử dụng từ khóa nào?',
  options: ['def', 'for', 'class', 'import'],
  correctAnswer: 'def',
  explanation: 'Từ khóa "def" trong Python dùng để định nghĩa một hàm mới, ví dụ: def ten_ham(tham_so):.',
  difficulty: 1,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-career-6',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-career',
  subject: 'informatics',
  prompt: 'Người làm công việc thiết kế, viết mã và kiểm thử các chương trình máy tính được gọi là gì?',
  options: ['Lập trình viên (Software Developer)', 'Quản trị mạng', 'Nhà thiết kế đồ hoạ', 'Nhân viên nhập liệu'],
  correctAnswer: 'Lập trình viên (Software Developer)',
  explanation: 'Lập trình viên (Software Developer) là người thiết kế, viết mã nguồn, kiểm thử và bảo trì các phần mềm, ứng dụng máy tính.',
  difficulty: 1,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-career-7',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-career',
  subject: 'informatics',
  prompt: 'Người chịu trách nhiệm quản lí, giám sát và đảm bảo an toàn cho hệ thống mạng máy tính của một tổ chức được gọi là gì?',
  options: ['Quản trị mạng (Network Administrator)', 'Nhà khoa học dữ liệu', 'Kĩ sư trí tuệ nhân tạo', 'Nhà thiết kế đa phương tiện'],
  correctAnswer: 'Quản trị mạng (Network Administrator)',
  explanation: 'Quản trị mạng (Network Administrator) chịu trách nhiệm cài đặt, vận hành, giám sát và bảo mật hệ thống mạng của tổ chức.',
  difficulty: 1,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-career-8',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-career',
  subject: 'informatics',
  prompt: 'Lĩnh vực nghiên cứu và phát triển các hệ thống máy tính có khả năng "học" và mô phỏng tư duy con người được gọi là gì?',
  options: ['Trí tuệ nhân tạo (AI)', 'Thiết kế đồ hoạ', 'Quản trị cơ sở dữ liệu', 'An toàn thông tin vật lí'],
  correctAnswer: 'Trí tuệ nhân tạo (AI)',
  explanation: 'Trí tuệ nhân tạo (Artificial Intelligence - AI) là lĩnh vực nghiên cứu, phát triển hệ thống máy tính mô phỏng khả năng học hỏi và tư duy của con người.',
  difficulty: 1,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-career-9',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-career',
  subject: 'informatics',
  prompt: 'Nhà khoa học dữ liệu (Data Scientist) thường làm công việc chính nào?',
  options: ['Thu thập, phân tích dữ liệu để rút ra thông tin và xu hướng hữu ích', 'Thiết kế giao diện người dùng', 'Sửa chữa phần cứng máy tính', 'Quản lí kho hàng vật lí'],
  correctAnswer: 'Thu thập, phân tích dữ liệu để rút ra thông tin và xu hướng hữu ích',
  explanation: 'Nhà khoa học dữ liệu chuyên thu thập, xử lí, phân tích lượng lớn dữ liệu để tìm ra quy luật, xu hướng phục vụ cho việc ra quyết định.',
  difficulty: 2,
  source: 'GDPT 2018 - Tin học lớp 9',
},
{
  id: 'gk-inf-career-10',
  type: 'mcq',
  category: 'informatics',
  topicId: 'inf-career',
  subject: 'informatics',
  prompt: 'Nhà thiết kế đa phương tiện (Multimedia Designer) thường làm việc với những loại nội dung nào?',
  options: ['Hình ảnh, âm thanh, video và hiệu ứng đồ hoạ', 'Chỉ với văn bản thuần túy', 'Chỉ với số liệu tài chính', 'Chỉ với mã nguồn phần mềm hệ thống'],
  correctAnswer: 'Hình ảnh, âm thanh, video và hiệu ứng đồ hoạ',
  explanation: 'Nhà thiết kế đa phương tiện làm việc với nhiều loại nội dung số như hình ảnh, âm thanh, video, hoạt hình để tạo ra sản phẩm truyền thông sáng tạo.',
  difficulty: 1,
  source: 'GDPT 2018 - Tin học lớp 9',
},
